"""Seed script: Clear all data and load Nexora Digital Solutions data"""
import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import uuid
import os

MONGO_URL = "mongodb://localhost:27017"
DB_NAME = None

# Read DB_NAME from .env
with open('/app/backend/.env') as f:
    for line in f:
        if line.startswith('DB_NAME'):
            DB_NAME = line.strip().split('=', 1)[1].strip('"').strip("'")
        if line.startswith('MONGO_URL'):
            MONGO_URL = line.strip().split('=', 1)[1].strip('"').strip("'")

CO = {
    "company_name": "Nexora Digital Solutions Pvt. Ltd.",
    "legal_name": "Nexora Digital Solutions Pvt. Ltd.",
    "short_name": "Nexora",
    "cin": "U72200GJ2019PTC108341",
    "gstin": "24AABCN4567P1Z8",
    "gstin_ahm": "24AABCN4567P1Z8",
    "gstin_blr": "29AABCN4567P1Z1",
    "pan": "AABCN4567P",
    "tan": "AHDN12345E",
    "stpi_reg": "STPI/AHM/2021/0087",
    "state": "Gujarat",
    "state_code": "24",
    "country": "India",
    "address": "Prahlad Nagar, Ahmedabad - 380015",
    "delivery_center": "Whitefield, Bengaluru - 560066",
    "period": "March 2026 (FY-end)",
    "services": "Custom Software Dev, IT Consulting, Managed Services, Data Analytics, Cloud & DevOps",
    "rev_model": "Fixed-Price (POC) | Time & Material | Monthly Retainer | Milestone-based",
    "billing_currency": "INR, USD, GBP",
    "usd_rate": 84.50,
    "gbp_rate": 106.80,
    "tax_regime": "Sec 115BAA - 25.17% Corp Tax; STPI Export exempt u/s 10AA",
}

PROJECTS = [
    {"id":"PRJ-001","name":"FinTrack Portal","client":"Axis Securities Ltd","client_id":"C001","type":"Fixed-Price","value_inr":4500000,"currency":"INR","duration":"Oct 25-Mar 26","pct_complete":88,"billing":"Milestone+Adv","pm":"Ravi Kapoor","pm_id":"E002","team":["E005","E006","E011","E012"],"team_names":["Sneha Joshi","Amit Rathod","Divya Mehta","Kiran Pillai"],"status":"88% complete","health":"GREEN","milestones":[{"id":"M1","name":"Requirements & Architecture","value":900000,"pct":20,"status":"Completed","date":"2025-11-15"},{"id":"M2","name":"Core Modules Development","value":1350000,"pct":30,"status":"Completed","date":"2026-01-20"},{"id":"M3","name":"Payment Gateway Integration","value":1350000,"pct":30,"status":"Completed","date":"2026-03-18"},{"id":"M4","name":"UAT & Go-Live","value":900000,"pct":20,"status":"In Progress","date":"2026-04-15"}]},
    {"id":"PRJ-002","name":"Cloud Migration Suite","client":"Mahindra Logistics Ltd","client_id":"C002","type":"T&M","value_inr":None,"currency":"USD","rate":"USD 95/hr offshore | USD 145/hr onsite","billing":"Monthly actuals","pm":"Priya Menon","pm_id":"E003","team":["E007","E008","E013"],"team_names":["Rahul Dev","Suresh Babu","Fatima Khan"],"status":"Ongoing","health":"YELLOW","duration":"Ongoing"},
    {"id":"PRJ-003","name":"Analytics Dashboard","client":"HDFC AMC","client_id":"C003","type":"Fixed-Price Milestone","value_inr":2800000,"currency":"INR","duration":"Jan 26-Jun 26","milestones_count":4,"billing":"Milestone","pm":"Ravi Kapoor","pm_id":"E002","team":["E009","E010","E011"],"team_names":["Ananya Singh","Siddharth Roy","Divya Mehta"],"status":"M2 delivered","health":"GREEN","pct_complete":50,"milestones":[{"id":"M1","name":"Data Architecture","value":700000,"pct":25,"status":"Completed","date":"2026-02-15"},{"id":"M2","name":"Data Ingestion + Reports","value":700000,"pct":25,"status":"Completed","date":"2026-03-07"},{"id":"M3","name":"Advanced Analytics","value":700000,"pct":25,"status":"Pending"},{"id":"M4","name":"ESG Module + Go-Live","value":700000,"pct":25,"status":"Pending"}]},
    {"id":"PRJ-004","name":"IT Managed Services","client":"Havells India Ltd","client_id":"C004","type":"Monthly Retainer","value_inr":450000,"currency":"INR","duration":"Apr 25-Mar 27","billing":"Monthly prepaid","pm":"Pooja Sharma","pm_id":"E004","team":["E008","E012","E016"],"team_names":["Suresh Babu","Kiran Pillai","Om Tiwari"],"status":"Active","health":"GREEN","pct_complete":None},
    {"id":"PRJ-005","name":"PayEdge Mobile App","client":"TechFin Corp USA","client_id":"C005","type":"Fixed-Price Export","value_inr":None,"value_usd":120000,"currency":"USD","duration":"Aug 25-Mar 26","billing":"30% Adv + Milestone","pm":"Priya Menon","pm_id":"E003","team":["E005","E006","E014","E015"],"team_names":["Sneha Joshi","Amit Rathod","Meera Das","Yash Trivedi"],"status":"CLOSED","health":"GREEN","pct_complete":100,"milestones":[{"id":"M1","name":"UI/UX + Architecture","value":24000,"pct":20,"status":"Completed","currency":"USD"},{"id":"M2","name":"Core Features","value":30000,"pct":25,"status":"Completed","currency":"USD"},{"id":"M3","name":"Backend + API","value":30000,"pct":25,"status":"Completed","currency":"USD"},{"id":"M4","name":"UAT + App Store","value":36000,"pct":30,"status":"Completed","date":"2026-03-22","currency":"USD"}]},
    {"id":"PRJ-006","name":"DevOps Transformation","client":"RetailCo PLC UK","client_id":"C006","type":"T&M Export","value_inr":None,"currency":"GBP","rate":"GBP 140/hr","billing":"Bi-monthly actuals","pm":"Ravi Kapoor","pm_id":"E002","team":["E007","E016"],"team_names":["Rahul Dev","Om Tiwari"],"status":"Ongoing","health":"GREEN","duration":"Ongoing"},
    {"id":"PRJ-007","name":"Data Warehouse Build","client":"Asian Paints Innovation","client_id":"C007","type":"Fixed-Price Milestone","value_inr":1800000,"currency":"INR","duration":"Feb 26-Jul 26","milestones_count":3,"billing":"Milestone","pm":"Pooja Sharma","pm_id":"E004","team":["E010","E009","E013"],"team_names":["Siddharth Roy","Ananya Singh","Fatima Khan"],"status":"M1 accepted","health":"GREEN","pct_complete":33,"milestones":[{"id":"M1","name":"Data Architecture Design","value":600000,"pct":33,"status":"Completed","date":"2026-03-25"},{"id":"M2","name":"ETL Pipeline Build","value":600000,"pct":33,"status":"Pending"},{"id":"M3","name":"Dashboard + Go-Live","value":600000,"pct":34,"status":"Pending"}]},
    {"id":"PRJ-INT","name":"Internal / Bench","client":"Internal","client_id":None,"type":"Non-billable","value_inr":0,"currency":"INR","billing":"N/A","pm":"Ravi Kapoor","pm_id":"E002","team":["All"],"team_names":["All"],"status":"Always open","health":"GREEN","pct_complete":None},
]

EMPLOYEES = [
    {"id":"E001","name":"Harsh Mehra","role":"CEO & MD","dept":"Leadership","ctc":420000,"bill_rate":None,"location":"Ahmedabad","billable":False},
    {"id":"E002","name":"Ravi Kapoor","role":"Delivery Head / PM","dept":"Delivery","ctc":185000,"bill_rate":95,"location":"Ahmedabad","billable":True},
    {"id":"E003","name":"Priya Menon","role":"Senior PM","dept":"Delivery","ctc":155000,"bill_rate":85,"location":"Bengaluru","billable":True},
    {"id":"E004","name":"Pooja Sharma","role":"PM - Managed Svcs","dept":"Delivery","ctc":120000,"bill_rate":75,"location":"Ahmedabad","billable":True},
    {"id":"E005","name":"Sneha Joshi","role":"Sr. Software Eng","dept":"Engineering","ctc":108000,"bill_rate":65,"location":"Ahmedabad","billable":True},
    {"id":"E006","name":"Amit Rathod","role":"Software Engineer","dept":"Engineering","ctc":82000,"bill_rate":50,"location":"Ahmedabad","billable":True},
    {"id":"E007","name":"Rahul Dev","role":"Cloud Architect","dept":"Engineering","ctc":145000,"bill_rate":90,"location":"Bengaluru","billable":True},
    {"id":"E008","name":"Suresh Babu","role":"DevOps Engineer","dept":"Engineering","ctc":95000,"bill_rate":60,"location":"Bengaluru","billable":True},
    {"id":"E009","name":"Ananya Singh","role":"Data Analyst","dept":"Analytics","ctc":88000,"bill_rate":55,"location":"Ahmedabad","billable":True},
    {"id":"E010","name":"Siddharth Roy","role":"Sr. Data Engineer","dept":"Analytics","ctc":112000,"bill_rate":70,"location":"Bengaluru","billable":True},
    {"id":"E011","name":"Divya Mehta","role":"QA Lead","dept":"QA","ctc":78000,"bill_rate":48,"location":"Ahmedabad","billable":True},
    {"id":"E012","name":"Kiran Pillai","role":"Business Analyst","dept":"BA","ctc":92000,"bill_rate":58,"location":"Ahmedabad","billable":True},
    {"id":"E013","name":"Fatima Khan","role":"Software Engineer","dept":"Engineering","ctc":76000,"bill_rate":46,"location":"Bengaluru","billable":True},
    {"id":"E014","name":"Meera Das","role":"UI/UX Designer","dept":"Design","ctc":72000,"bill_rate":44,"location":"Ahmedabad","billable":True},
    {"id":"E015","name":"Yash Trivedi","role":"Mobile Developer","dept":"Engineering","ctc":85000,"bill_rate":52,"location":"Ahmedabad","billable":True},
    {"id":"E016","name":"Om Tiwari","role":"DevOps Engineer","dept":"Engineering","ctc":80000,"bill_rate":50,"location":"Bengaluru","billable":True},
    {"id":"E017","name":"Nisha Agarwal","role":"Finance Manager","dept":"Finance","ctc":110000,"bill_rate":None,"location":"Ahmedabad","billable":False},
    {"id":"E018","name":"Lakshmi R.","role":"HR Manager","dept":"HR","ctc":85000,"bill_rate":None,"location":"Bengaluru","billable":False},
    {"id":"E019","name":"Vikram Jain","role":"Sales Manager","dept":"Sales","ctc":125000,"bill_rate":None,"location":"Ahmedabad","billable":False},
    {"id":"E020","name":"Tanvi Shah","role":"Inside Sales Exec","dept":"Sales","ctc":55000,"bill_rate":None,"location":"Ahmedabad","billable":False},
]

CLIENTS = [
    {"id":"C001","entity_type":"customer","name":"Axis Securities Ltd","segment":"BFSI","city":"Mumbai","state":"Maharashtra","state_code":"27","gstin":"27AAACA8901Z1Z3","credit_limit":2500000,"currency":"INR","payment_terms":"Net 30"},
    {"id":"C002","entity_type":"customer","name":"Mahindra Logistics Ltd","segment":"Logistics","city":"Mumbai","state":"Maharashtra","state_code":"27","gstin":"27AABCM5432Z1Z9","credit_limit":4000000,"currency":"USD","payment_terms":"Net 30"},
    {"id":"C003","entity_type":"customer","name":"HDFC AMC","segment":"Asset Management","city":"Mumbai","state":"Maharashtra","state_code":"27","gstin":"27AABCH6789Z1Z4","credit_limit":2000000,"currency":"INR","payment_terms":"Net 30"},
    {"id":"C004","entity_type":"customer","name":"Havells India Ltd","segment":"Manufacturing","city":"Noida","state":"Uttar Pradesh","state_code":"09","gstin":"09AAACH3456Z1Z7","credit_limit":1000000,"currency":"INR","payment_terms":"Monthly prepaid"},
    {"id":"C005","entity_type":"customer","name":"TechFin Corp","segment":"FinTech Export","city":"Austin, US","state":"Export","state_code":"99","gstin":"EXPORT","credit_limit":6000000,"currency":"USD","payment_terms":"Milestone"},
    {"id":"C006","entity_type":"customer","name":"RetailCo PLC","segment":"Retail Export","city":"London, UK","state":"Export","state_code":"99","gstin":"EXPORT","credit_limit":5000000,"currency":"GBP","payment_terms":"Bi-monthly"},
    {"id":"C007","entity_type":"customer","name":"Asian Paints Innovation","segment":"Manufacturing","city":"Mumbai","state":"Maharashtra","state_code":"27","gstin":"27AAACA1234Z1Z2","credit_limit":1200000,"currency":"INR","payment_terms":"Net 30"},
]

VENDORS = [
    {"id":"V001","entity_type":"vendor","name":"Microsoft India (Azure)","category":"Cloud Infra","payment_terms":"Monthly","tds_section":"194J","gstin":"27AAACM1234Z1Z5","state":"Maharashtra","state_code":"27"},
    {"id":"V002","entity_type":"vendor","name":"AWS India Pvt. Ltd.","category":"Cloud Infra","payment_terms":"Monthly","tds_section":"194J","gstin":"27AABCA5678Z1Z3","state":"Maharashtra","state_code":"27"},
    {"id":"V003","entity_type":"vendor","name":"Atlassian (Jira/Confluence)","category":"SaaS Tools","payment_terms":"Annual","tds_section":"194J","gstin":"IMPORT","state":"Export","state_code":"99"},
    {"id":"V004","entity_type":"vendor","name":"GitHub Enterprise","category":"Dev Tools","payment_terms":"Annual","tds_section":"194J","gstin":"IMPORT","state":"Export","state_code":"99"},
    {"id":"V005","entity_type":"vendor","name":"Zoho Corp","category":"CRM/ERP","payment_terms":"Annual","tds_section":"194J","gstin":"33AABCZ1234Z1Z5","state":"Tamil Nadu","state_code":"33"},
    {"id":"V006","entity_type":"vendor","name":"InfoSys BPM (Subcontract)","category":"Sub-contractor","payment_terms":"Net 30","tds_section":"194C","gstin":"29AABCI5678Z1Z8","state":"Karnataka","state_code":"29"},
    {"id":"V007","entity_type":"vendor","name":"FreeAgent Devs LLP","category":"Freelancers","payment_terms":"Net 15","tds_section":"194C","gstin":"24AABCF9012Z1Z4","state":"Gujarat","state_code":"24"},
    {"id":"V008","entity_type":"vendor","name":"Deloitte India (Audit)","category":"Professional Svcs","payment_terms":"Net 30","tds_section":"194J","gstin":"27AABCD3456Z1Z6","state":"Maharashtra","state_code":"27"},
    {"id":"V009","entity_type":"vendor","name":"Network18 Media (Marketing)","category":"Marketing","payment_terms":"Net 30","tds_section":"194C","gstin":"27AABCN7890Z1Z2","state":"Maharashtra","state_code":"27"},
    {"id":"V010","entity_type":"vendor","name":"Regus (Co-working, BLR)","category":"Office/Infra","payment_terms":"Monthly","tds_section":"194I","gstin":"29AABCR2345Z1Z1","state":"Karnataka","state_code":"29"},
]

REV_SCHEDULE = [
    {"project_id":"PRJ-001","project_name":"FinTrack Portal","method":"POC - Cost Incurred","total":4500000,"pct_feb":72,"pct_mar":88,"rev_feb":3240000,"rev_mar":3960000,"billed_to_mar":3800000,"contract_asset":160000,"contract_liability":0,"comment":"FP project; revenue = total x % complete. Mar revenue > billed = accrued."},
    {"project_id":"PRJ-002","project_name":"Cloud Migration Suite","method":"T&M Actuals","total":None,"pct_feb":None,"pct_mar":None,"rev_feb":None,"rev_mar":2247700,"billed_to_mar":2247700,"contract_asset":0,"contract_liability":0,"comment":"Revenue = hours x rate billed monthly."},
    {"project_id":"PRJ-003","project_name":"Analytics Dashboard","method":"Milestone","total":2800000,"pct_feb":25,"pct_mar":50,"rev_feb":700000,"rev_mar":1400000,"billed_to_mar":700000,"contract_asset":700000,"contract_liability":0,"comment":"M2 completed Mar - revenue recognized but invoice raised. M1 invoiced."},
    {"project_id":"PRJ-004","project_name":"IT Managed Services","method":"Straight-Line Retainer","total":5400000,"pct_feb":None,"pct_mar":None,"rev_feb":450000,"rev_mar":450000,"billed_to_mar":450000,"contract_asset":0,"contract_liability":450000,"comment":"Invoice at month-start = advance. Recognize over month."},
    {"project_id":"PRJ-005","project_name":"PayEdge Mobile App","method":"POC - Milestone Hybrid","total":10140000,"pct_feb":85,"pct_mar":100,"rev_feb":8619000,"rev_mar":10140000,"billed_to_mar":10140000,"contract_asset":0,"contract_liability":0,"comment":"USD 120,000. M4 final delivery Mar. Project CLOSED."},
    {"project_id":"PRJ-006","project_name":"DevOps Transformation","method":"T&M Export","total":None,"pct_feb":None,"pct_mar":None,"rev_feb":1794240,"rev_mar":3349248,"billed_to_mar":5141488,"contract_asset":0,"contract_liability":0,"comment":"GBP 140/hr billed bi-monthly. Feb+Mar combined invoice."},
    {"project_id":"PRJ-007","project_name":"Data Warehouse Build","method":"Milestone","total":1800000,"pct_feb":0,"pct_mar":33,"rev_feb":0,"rev_mar":600000,"billed_to_mar":0,"contract_asset":708000,"contract_liability":0,"comment":"M1 delivered 25-Mar but invoice NOT raised. Fully accrued (unbilled AR)."},
]

OPENING_TB = [
    # Assets
    {"account":"HDFC Bank - Current","type":"Bank","category":"Assets","sub_category":"Current Assets","debit":6840000,"credit":0,"note":"Primary ops account"},
    {"account":"Axis Bank - Current","type":"Bank","category":"Assets","sub_category":"Current Assets","debit":2250000,"credit":0,"note":"Secondary account"},
    {"account":"EEFC USD Account","type":"Bank/Forex","category":"Assets","sub_category":"Current Assets","debit":3042000,"credit":0,"note":"USD 36,000 x 84.50"},
    {"account":"Billed Accounts Receivable","type":"AR","category":"Assets","sub_category":"Current Assets","debit":5830000,"credit":0,"note":"Client invoices outstanding"},
    {"account":"Unbilled AR (Contract Asset)","type":"Revenue Accrual","category":"Assets","sub_category":"Current Assets","debit":2410000,"credit":0,"note":"T&M and milestone earned, unbilled"},
    {"account":"TDS Receivable","type":"Tax Asset","category":"Assets","sub_category":"Current Assets","debit":680000,"credit":0,"note":"From clients (26AS match)"},
    {"account":"Advance Tax Paid","type":"Tax Asset","category":"Assets","sub_category":"Current Assets","debit":2800000,"credit":0,"note":"Q1-Q3 advance tax FY26"},
    {"account":"Prepaid Expenses","type":"Current Asset","category":"Assets","sub_category":"Current Assets","debit":850000,"credit":0,"note":"Software licenses, subscriptions"},
    {"account":"Fixed Assets - IT Equip (Gross)","type":"Fixed Asset","category":"Assets","sub_category":"Non-Current Assets","debit":1850000,"credit":0,"note":"21 laptops + office equipment"},
    {"account":"Accumulated Depreciation","type":"Fixed Asset","category":"Assets","sub_category":"Non-Current Assets","debit":0,"credit":720000,"note":"Cumulative till Feb 26"},
    {"account":"ROU Asset - BLR Office","type":"Lease","category":"Assets","sub_category":"Non-Current Assets","debit":1240000,"credit":0,"note":"Ind AS 116 - Regus co-working"},
    {"account":"Security Deposits","type":"Non-current","category":"Assets","sub_category":"Non-Current Assets","debit":350000,"credit":0,"note":"Office and utility deposits"},
    # Liabilities
    {"account":"Accounts Payable","type":"Creditors","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":1420000,"note":"Vendor invoices outstanding"},
    {"account":"Deferred Revenue (Contract Liability)","type":"Revenue","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":1840000,"note":"Advance billing > revenue earned"},
    {"account":"Advance from Customers","type":"Customer Adv","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":450000,"note":"Havells March retainer advance"},
    {"account":"Lease Liability - BLR","type":"Lease","category":"Liabilities","sub_category":"Non-Current Liabilities","debit":0,"credit":1180000,"note":"Ind AS 116 lease obligation"},
    {"account":"Salary Payable","type":"Payroll","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":320000,"note":"Feb net salary pending"},
    {"account":"TDS Payable","type":"Tax","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":283620,"note":"Feb deductions not remitted"},
    {"account":"PF Payable","type":"Statutory","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":191250,"note":"Feb PF not remitted"},
    {"account":"Provision for Gratuity","type":"Provision","category":"Liabilities","sub_category":"Non-Current Liabilities","debit":0,"credit":480000,"note":"Actuarial liability till Feb"},
    {"account":"Leave Encashment Provision","type":"Provision","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":210000,"note":"Unutilized leave liability"},
    {"account":"Accrued Expenses","type":"Accruals","category":"Liabilities","sub_category":"Current Liabilities","debit":0,"credit":360000,"note":"Sub-contractor, cloud accruals"},
    # Equity
    {"account":"Share Capital","type":"Equity","category":"Equity","sub_category":"Share Capital","debit":0,"credit":5000000,"note":"Authorized and paid-up"},
    {"account":"Securities Premium","type":"Equity","category":"Equity","sub_category":"Reserves","debit":0,"credit":8000000,"note":"Angel + Series-A premium"},
    {"account":"ESOP Reserve","type":"Equity","category":"Equity","sub_category":"Reserves","debit":0,"credit":820000,"note":"Accumulated ESOP expense"},
    {"account":"Retained Earnings (P&L)","type":"Equity","category":"Equity","sub_category":"Retained Earnings","debit":0,"credit":7537130,"note":"Cumulative PAT till Feb 2026"},
]

TRANSACTIONS = [
    {"id":"T001","date":"02-Mar-26","module":"CRM","type":"Lead Creation","priority":"High","prompt":"Create Lead: 'RBL Bank - Digital Banking Division', Contact: Sameer Pathak (CTO), Phone: 9820445566, Email: s.pathak@rblbank.com, Source: Nasscom event (BangaloreTech Summit), Interest: Digital lending workflow automation (custom dev), Est. Value: Rs.55,00,000, Duration: 12 months, Stage: New. Assign to Vikram Jain.","accounting":"No entry","integrity":"Lead pipeline tracking"},
    {"id":"T002","date":"03-Mar-26","module":"CRM","type":"Lead - RFP Received","priority":"Critical","prompt":"RBL Bank Lead upgraded: RFP received (RFP/RBLB/2026/IT/022). Response deadline: 20-Mar-26. Assign pre-sales team: Ravi Kapoor (Delivery) + Vikram Jain (Sales) + Priya Menon (Technical). Log RFP document, schedule internal review call 06-Mar. Stage: RFP Response. Probability 40%.","accounting":"No entry - pre-sales cost to be tracked","integrity":"RFP opportunity management"},
    {"id":"T003","date":"04-Mar-26","module":"CRM","type":"Opportunity - RetailCo Expansion","priority":"High","prompt":"Existing client RetailCo PLC UK (C006) requested scope expansion for DevOps project (PRJ-006): Add 2 extra DevOps engineers for 3 months. Additional SOW value: GBP 140/hr x 2 engineers x 480 hrs = GBP 1,34,400. Create change-request opportunity CR-006-001 linked to PRJ-006. Stage: Negotiation. Probability: 85%.","accounting":"No entry yet - pending SOW","integrity":"Change request pipeline"},
    {"id":"T004","date":"05-Mar-26","module":"CRM","type":"New Lead - AI Product","priority":"Normal","prompt":"Create Lead: 'Tata Digital - AI CoE', Contact: Priya Iyer (Head of AI), Source: LinkedIn outreach by Tanvi Shah, Interest: Gen-AI powered customer support bot, Est. Value: Rs.80,00,000, Stage: New. Note: Highly competitive - 4 vendors shortlisted. Assign to Vikram Jain. Add to Q1 FY27 pipeline.","accounting":"No entry","integrity":"New pipeline"},
    {"id":"T005","date":"07-Mar-26","module":"CRM","type":"Proposal Submission","priority":"Critical","prompt":"Submit RFP response for RBL Bank: Technical proposal (60 pages) + Commercial proposal (Rs.52,00,000 fixed price, 11 months). Approach: Agile sprints, offshore-first. Payment: 20% mobilization + 4 quarterly milestones. Submit via portal. Record submission date for follow-up.","accounting":"Pre-sales expense: Ravi Kapoor 12 hrs + Priya Menon 8 hrs = 20 hrs internal cost Rs.57,200","integrity":"Proposal cost tracking"},
    {"id":"T006","date":"10-Mar-26","module":"CRM","type":"Lead Won - RetailCo SOW","priority":"Critical","prompt":"Mark CR-006-001 as WON. RetailCo confirmed additional 2 engineers from 15-Mar. Signed SOW amendment SOW-006-A1. Additional billing: GBP 140/hr per engineer. Add Om Tiwari (E016) and freelancer Arun Nair (FreeAgent Devs V007) to PRJ-006. Update project team and billing plan.","accounting":"No accounting entry - SOW signed; billing starts 15-Mar","integrity":"SOW amendment - resource add"},
    {"id":"T007","date":"12-Mar-26","module":"CRM","type":"Lead - Demo Scheduled","priority":"Normal","prompt":"Tata Digital AI lead: Product demo scheduled 18-Mar at Tata House, Mumbai. Prepare demo environment: deploy Nexora AI bot prototype on Azure. Assign: Rahul Dev (cloud setup) 4 hrs + Ananya Singh (data config) 3 hrs + Sneha Joshi (demo lead) 6 hrs = 13 hrs pre-sales effort. Log as non-billable / BD activity.","accounting":"Pre-sales effort: log 13 hrs to PRJ-INT (Business Dev)","integrity":"Pre-sales cost tracking"},
    {"id":"T008","date":"14-Mar-26","module":"CRM","type":"Existing Client - Upsell","priority":"Normal","prompt":"HDFC AMC (C003, PRJ-003) requested additional module: ESG Scoring Analytics add-on. Quotation QT-2026-009 sent: Rs.4,50,000 fixed price, 2-month extension. If approved, raise change order CO-003-001 to existing SOW. Stage: Proposal Sent. Probability: 70%.","accounting":"No entry - quoted","integrity":"Upsell on existing project"},
    {"id":"T009","date":"16-Mar-26","module":"CRM","type":"RBL Bank - Shortlisted","priority":"Critical","prompt":"RBL Bank confirms Nexora shortlisted (top 2 of 6 vendors). Presentation scheduled 25-Mar. Prepare: Updated pricing (MD Harsh Mehra to decide on 5% discount to Rs.49,40,000). Internal approval required. Log activity. Stage: Commercial Negotiation.","accounting":"No entry","integrity":"Negotiation tracking"},
    {"id":"T010","date":"18-Mar-26","module":"CRM","type":"Demo - Tata Digital","priority":"Normal","prompt":"Tata Digital demo conducted at Mumbai. Feedback: Positive on NLP accuracy, concern on data privacy (on-premise requirement). Follow-up action: Provide on-premise deployment architecture doc by 25-Mar. Assign: Rahul Dev. Stage: Technical Evaluation. Probability revised to 55%.","accounting":"Travel expense: Vikram Jain + Sneha Joshi Mumbai visit Rs.24,500. Dr Selling Expense | Cr Bank.","integrity":"Demo cost"},
    {"id":"T011","date":"20-Mar-26","module":"CRM","type":"Lost Deal","priority":"Normal","prompt":"Log lost deal: 'Biocon IT Modernization' (pipeline since Jan). Lost to TCS. Reason: incumbency advantage (TCS existing vendor). Lost deal value: Rs.35,00,000. Analyse: pricing competitive, lost on relationship. Document in CRM. Update pipeline. Inform MD.","accounting":"No entry - pipeline write-off","integrity":"Lost deal analytics"},
    {"id":"T012","date":"22-Mar-26","module":"CRM","type":"Havells Renewal","priority":"High","prompt":"Havells India (C004, PRJ-004) retainer contract renewal: Current contract ends 31-Mar-27 (still active). Renewal discussion initiated 12 months early - client wants 10% price increase. Counter-proposal: 7% increase Rs.4,81,500/month for 2-year lock-in. Log negotiation.","accounting":"No entry - future contract","integrity":"Renewal pipeline"},
    {"id":"T013","date":"25-Mar-26","module":"CRM","type":"RBL Bank Presentation","priority":"Critical","prompt":"Final presentation to RBL Bank Board. MD Harsh Mehra + Ravi Kapoor attended. Final price: Rs.49,40,000. Payment: 20% advance Rs.9,88,000 + 4 milestones of Rs.9,88,000 each. Decision expected by 05-Apr. Probability: 75%. Stage: Awaiting PO.","accounting":"No entry","integrity":"BD pipeline close"},
    {"id":"T014","date":"28-Mar-26","module":"CRM","type":"HDFC AMC Change Order Won","priority":"Normal","prompt":"HDFC AMC (C003) approved ESG add-on change order CO-003-001: Rs.4,50,000. Raise SOW amendment. Extend PRJ-003 timeline by 6 weeks. Add Ananya Singh as primary resource. April start. Post in CRM as won. Convert to project extension.","accounting":"No entry - project extension; billing Apr onwards","integrity":"Change order to project"},
    {"id":"T015","date":"31-Mar-26","module":"CRM","type":"Monthly Pipeline Report","priority":"Normal","prompt":"Generate March 2026 CRM Pipeline Report: New leads: 3. Won: 2 (RetailCo SOW amendment, HDFC change order). Lost: 1 (Biocon). Proposals outstanding: 2 (RBL Bank, Tata Digital). Total qualified pipeline value: Rs.1,84,40,000. Win rate YTD FY26: 58%. Average deal size: Rs.42,00,000.","accounting":"No entry - management report","integrity":"Pipeline reconciliation"},
    {"id":"T016","date":"01-Mar-26","module":"Projects","type":"Project Status Update - PRJ-001","priority":"Critical","prompt":"Update PRJ-001 FinTrack Portal status for March: Completion at 01-Mar: 72%. Budget consumed: Rs.32,40,000 of Rs.45,00,000. Sprint 8 in progress. Key milestone M3 (Payment Gateway Integration) targeted 20-Mar. Risk: API dependency on Axis Securities internal team causing 5-day delay.","accounting":"Revenue recognized to date: Rs.32,40,000 (72% of Rs.45L). Deferred revenue on balance sheet.","integrity":"POC status - revenue recognition"},
    {"id":"T017","date":"01-Mar-26","module":"Projects","type":"Project Setup - PRJ-006 SOW Amend","priority":"High","prompt":"Update PRJ-006 DevOps Transformation per SOW amendment: Add 2 additional resources from 15-Mar. Add Om Tiwari (E016) and FreeAgent Devs (V007 sub-contract). Update billing plan: existing Rahul Dev 140 GBP/hr + Om Tiwari 140 GBP/hr + FreeAgent (internal sub 140 GBP/hr billed, cost: Rs.45,000/month). Update project budget.","accounting":"Sub-contractor cost to be accrued as incurred","integrity":"Resource plan update"},
    {"id":"T018","date":"02-Mar-26","module":"Projects","type":"Milestone - PRJ-003 M2 Review","priority":"Critical","prompt":"PRJ-003 Analytics Dashboard: Milestone M2 (Data Ingestion Layer + 5 Standard Reports) reviewed with HDFC AMC on 02-Mar. Client acceptance: CONDITIONAL - 3 minor bugs in report formatting. Fix timeline: 7-Mar. Once sign-off received, trigger M2 invoice (Rs.7,00,000 = 25% of Rs.28L). Revenue deferred until sign-off.","accounting":"Revenue on hold pending sign-off. Once signed: Dr Unbilled AR / AR -> recognize Rs.7,00,000","integrity":"Milestone acceptance - revenue trigger"},
    {"id":"T019","date":"05-Mar-26","module":"Projects","type":"Budget vs Actual - PRJ-002","priority":"Normal","prompt":"PRJ-002 Cloud Migration (Mahindra): Review Feb actuals vs budget. Budget Feb: 320 hrs (USD 30,400). Actual Feb: 298 hrs (USD 28,310) - under-utilized by 22 hrs. Revenue = 298 hrs billed. March plan: 350 hrs target. Log project health: YELLOW.","accounting":"Feb hours billed: USD 28,310 x Rs.84.50 = Rs.23,92,195","integrity":"T&M budget vs actual"},
    {"id":"T020","date":"07-Mar-26","module":"Projects","type":"M2 Sign-off - PRJ-003","priority":"Critical","prompt":"HDFC AMC signed M2 Acceptance Certificate (AC-003-M2, dated 07-Mar-26) after bug fixes. M2 officially delivered. Trigger revenue recognition for M2: Rs.7,00,000. Raise invoice INV-DOM-2026-031 for Rs.7,00,000 + GST 18% = Rs.8,26,000. Update project completion to 50%.","accounting":"Dr AR Rs.8,26,000 | Cr Revenue Rs.7,00,000 + GST Output Rs.1,26,000; M2 contract asset cleared","integrity":"Milestone sign-off to revenue"},
    {"id":"T021","date":"10-Mar-26","module":"Projects","type":"PRJ-005 Final Delivery Prep","priority":"Critical","prompt":"PRJ-005 PayEdge Mobile App (TechFin USA): Final delivery prep - M4 (App Store submission + UAT sign-off). Completion target: 25-Mar. Revenue to be recognized: Total USD 1,20,000 = Rs.1,01,40,000. Less already recognized: USD 90,000 (M1-M3). Final recognition: USD 30,000 = Rs.25,35,000.","accounting":"On M4 sign-off: Dr AR/Unbilled AR USD 30,000 x Rs.84.50 = Rs.25,35,000 | Cr Export Revenue","integrity":"Final milestone - export revenue"},
    {"id":"T022","date":"12-Mar-26","module":"Projects","type":"PRJ-007 M1 Delivery","priority":"High","prompt":"PRJ-007 Data Warehouse (Asian Paints): M1 (Data Architecture Design + Source System Mapping) delivered 12-Mar. PM Pooja Sharma submits for client review. M1 value: Rs.6,00,000 (33% of Rs.18L). Revenue recognizable on acceptance. Client review period: 10 business days.","accounting":"Recognize revenue on acceptance; until then: Contract Asset (unbilled) if costs incurred","integrity":"Milestone delivery - acceptance period"},
    {"id":"T023","date":"14-Mar-26","module":"Projects","type":"Project Cost Allocation","priority":"Normal","prompt":"Post project cost allocations for all active projects (direct cost of delivery): PRJ-001: Rs.5,40,000. PRJ-002: Cloud infra cost USD 2,800 = Rs.2,36,600. PRJ-003: Rs.3,20,000. PRJ-004: Rs.1,80,000. PRJ-005: Rs.4,10,000. PRJ-006: Rs.2,50,000 + sub-contract. PRJ-007: Rs.1,40,000. Post to project-wise P&L.","accounting":"Dr Project Direct Costs (per project) | Cr Salary Expense / Cloud Cost - allocation","integrity":"Cost allocation accuracy"},
    {"id":"T024","date":"15-Mar-26","module":"Projects","type":"Resource Reallocation","priority":"Normal","prompt":"Resource reallocation effective 15-Mar: Divya Mehta (QA Lead E011) moved from PRJ-001 (100%) to PRJ-001 (60%) + PRJ-003 (40%). Update resource plan and billing allocation. Timesheet split to be reflected.","accounting":"Timesheet-based billing; ensure split correctly reflected in project billing","integrity":"Resource split billing"},
    {"id":"T025","date":"18-Mar-26","module":"Projects","type":"PRJ-001 M3 Delivery","priority":"Critical","prompt":"PRJ-001 FinTrack Portal M3 (Payment Gateway Integration) delivered 18-Mar. POC updated to 88%. Revenue recognition: Rs.45,00,000 x 88% = Rs.39,60,000. Previously recognized: Rs.32,40,000. Incremental March revenue: Rs.7,20,000. M3 billing: raise invoice per milestone schedule. Acceptance certificate obtained.","accounting":"Recognize Rs.7,20,000 incremental revenue: Dr AR | Cr Revenue. Adjust deferred/contract asset.","integrity":"POC revenue increment"},
    {"id":"T026","date":"20-Mar-26","module":"Projects","type":"Scope Change - PRJ-001","priority":"High","prompt":"Axis Securities requests scope change on PRJ-001: Add PAN-Aadhaar KYC integration. Change order estimate: Rs.3,50,000 + 3 weeks extension. PM prepares change order CO-001-002. Pending client approval. Impact on revenue: POC recalculated on revised total Rs.48,50,000 if approved.","accounting":"No accounting until approved; disclose as contingent asset","integrity":"Scope change - contract modification"},
    {"id":"T027","date":"22-Mar-26","module":"Projects","type":"PRJ-005 Final Sign-off","priority":"Critical","prompt":"TechFin USA signed final acceptance certificate for PRJ-005 PayEdge (UAT passed, App Store approved). M4 complete. POC = 100%. Final revenue: USD 30,000 x Rs.84.50 = Rs.25,35,000. Close project. Final invoice USD 30,000 to be raised. Advance USD 36,000 applied across milestones.","accounting":"Dr Export AR USD 30,000 x Rs.84.50 = Rs.25,35,000 | Cr Export Revenue; IGST nil (LUT/STPI)","integrity":"Export project closure"},
    {"id":"T028","date":"25-Mar-26","module":"Projects","type":"PRJ-007 M1 Accepted","priority":"High","prompt":"Asian Paints accepted PRJ-007 M1 (Data Architecture sign-off, AC-007-M1 dated 25-Mar). Revenue recognized: Rs.6,00,000. Invoice NOT raised yet (scheduled 03-Apr). Post revenue as ACCRUED REVENUE (Unbilled AR) for March FY-end. Critical for correct FY-end P&L.","accounting":"Dr Unbilled AR (Accrued Revenue) Rs.7,08,000 | Cr Revenue Rs.6,00,000 + GST payable Rs.1,08,000","integrity":"Unbilled AR - FY-end cut-off critical"},
    {"id":"T029","date":"28-Mar-26","module":"Projects","type":"Project Health Dashboard","priority":"Normal","prompt":"Generate March 2026 Project Health Dashboard: PRJ-001: GREEN (88% complete). PRJ-002: YELLOW (access delays). PRJ-003: GREEN (50% M2 done). PRJ-004: GREEN (retainer stable). PRJ-005: CLOSED. PRJ-006: GREEN. PRJ-007: GREEN (M1 done). Report to MD.","accounting":"Management reporting","integrity":"Portfolio health"},
    {"id":"T030","date":"31-Mar-26","module":"Projects","type":"WIP & Contract Assets Review","priority":"Critical","prompt":"Review all contract assets (unbilled revenue) and contract liabilities (deferred revenue) as at 31-Mar-26. Ind AS 115 compliant B/S presentation. Unbilled AR: PRJ-007 M1 Rs.7,08,000. Deferred Revenue: PRJ-001 over-billing + PRJ-004 advance.","accounting":"Contract assets vs contract liabilities - Ind AS 115 B/S classification","integrity":"Revenue balances FY-end"},
    {"id":"T031","date":"02-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Sneha Joshi","priority":"Normal","prompt":"Submit timesheet for Sneha Joshi (E005) - Week 1 (02-07 Mar): PRJ-001: 32 hrs billable. PRJ-INT/BD: 4 hrs non-billable (demo prep). PRJ-005: 4 hrs billable. Total: 40 hrs.","accounting":"Billable: PRJ-001 32hrs, PRJ-005 4hrs -> feed into billing calculation","integrity":"Timesheet completeness"},
    {"id":"T032","date":"02-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Amit Rathod","priority":"Normal","prompt":"Submit timesheet for Amit Rathod (E006) - Week 1 (02-07 Mar): PRJ-001: 36 hrs billable. PRJ-005: 4 hrs billable. Total: 40 hrs. 100% billable week. Note: 2 hrs OT on PRJ-001 Saturday.","accounting":"OT 2 hrs: special OT billing rate per Axis SOW (1.5x standard)","integrity":"OT timesheet tagging"},
    {"id":"T033","date":"02-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Rahul Dev","priority":"Normal","prompt":"Submit timesheet for Rahul Dev (E007) - Week 1: PRJ-002: 32 hrs billable (USD 95/hr). PRJ-006: 8 hrs billable (GBP 140/hr). Total: 40 hrs. Two projects, two currencies.","accounting":"PRJ-002: 32 hrs x USD 95 = USD 3,040. PRJ-006: 8 hrs x GBP 140 = GBP 1,120.","integrity":"Multi-currency timesheet"},
    {"id":"T034","date":"02-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Kiran Pillai","priority":"Normal","prompt":"Submit timesheet for Kiran Pillai (E012) - Week 1: PRJ-001: 24 hrs billable. PRJ-004: 12 hrs billable. PRJ-INT/Training: 4 hrs non-billable. Total: 40 hrs.","accounting":"Billable per SOW; Havells retainer covers all resource types","integrity":"SOW scope verification"},
    {"id":"T035","date":"02-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Ananya Singh","priority":"Normal","prompt":"Submit timesheet for Ananya Singh (E009) - Week 1: PRJ-003: 28 hrs billable. PRJ-007: 12 hrs billable. Total: 40 hrs. Two active projects.","accounting":"PRJ-003: 28 hrs; PRJ-007: 12 hrs","integrity":"Multi-project analyst"},
    {"id":"T036","date":"02-Mar-26","module":"Timesheets","type":"Timesheet - Bench Hours","priority":"Normal","prompt":"Log bench/non-billable hours for Week 1: Meera Das (E014) - 32 hrs Bench + 8 hrs training. Yash Trivedi (E015) - 20 hrs billable PRJ-005 + 20 hrs bench. Bench cost: Rs.30,192.","accounting":"Bench cost Dr Bench/Idle Overhead Rs.30,192 | Cr Salary allocation","integrity":"Bench utilization tracking"},
    {"id":"T037","date":"03-Mar-26","module":"Timesheets","type":"Timesheet Approval - PM","priority":"Normal","prompt":"PM Ravi Kapoor approves timesheets for PRJ-001 team (Week 1): Approved: Sneha Joshi 32 hrs, Amit Rathod 36 hrs, Kiran Pillai 24 hrs. Rejected: Divya Mehta - 40 hrs all to PRJ-001 but she was on leave 06-Mar. Send back for correction.","accounting":"Incorrect timesheet cannot be billed - correction required","integrity":"Timesheet approval workflow"},
    {"id":"T038","date":"04-Mar-26","module":"Timesheets","type":"Timesheet Correction","priority":"High","prompt":"Divya Mehta (E011) corrects timesheet: Remove 8 hrs (06-Mar - Sick Leave). Revised: PRJ-001: 32 hrs billable. Sick leave 8 hrs = SL (not billable). Resubmit for PM approval. PM reapproves.","accounting":"32 hrs billable to PRJ-001; SL hours = nil billing","integrity":"Leave vs timesheet reconciliation"},
    {"id":"T039","date":"09-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Week 2","priority":"Normal","prompt":"Submit Week 2 timesheets (09-14 Mar) for all engineers: Sneha Joshi: PRJ-001 32hrs + PRJ-005 8hrs. Amit Rathod: PRJ-001 40hrs. Rahul Dev: PRJ-002 24hrs + PRJ-006 16hrs. Suresh Babu: PRJ-004 32hrs + PRJ-002 8hrs. Om Tiwari: PRJ-INT 40hrs (training week, non-billable).","accounting":"Om Tiwari training week: non-billable, Dr Training Overhead | Cr Salary allocation","integrity":"Onboarding non-billable"},
    {"id":"T040","date":"09-Mar-26","module":"Timesheets","type":"Missing Timesheet Alert","priority":"High","prompt":"System alert: 3 employees have not submitted Week 1 timesheets: Fatima Khan (E013), Siddharth Roy (E010), Om Tiwari (E016). HR policy: timesheet due by Monday 9 AM. Automated reminder sent.","accounting":"No billing possible without timesheet - revenue at risk","integrity":"Timesheet compliance control"},
    {"id":"T041","date":"10-Mar-26","module":"Timesheets","type":"Late Timesheet Submission","priority":"Normal","prompt":"Fatima Khan and Siddharth Roy submit late Week 1 timesheets: Fatima: PRJ-002 20hrs + PRJ-007 20hrs. Siddharth: PRJ-003 28hrs + PRJ-007 12hrs. Both approved. Om Tiwari: 40 hrs New Employee Orientation (non-billable).","accounting":"Late but billable hours included in monthly billing","integrity":"Late timesheet - billing recovery"},
    {"id":"T042","date":"16-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Week 3","priority":"Normal","prompt":"Week 3 timesheets (16-21 Mar): Sneha Joshi: PRJ-001 40hrs (includes Saturday 4hrs OT). Amit Rathod: PRJ-001 36hrs + PRJ-005 4hrs. Rahul Dev: PRJ-002 16hrs + PRJ-006 24hrs. Om Tiwari: PRJ-006 24hrs (first billable week, GBP 140/hr). Ananya Singh: PRJ-003 32hrs + PRJ-007 8hrs.","accounting":"Om Tiwari Week 3 billable to RetailCo: 24 hrs x GBP 140 = GBP 3,360","integrity":"New resource billing commencement"},
    {"id":"T043","date":"16-Mar-26","module":"Timesheets","type":"Timesheet - FreeAgent Sub","priority":"High","prompt":"FreeAgent Devs LLP (V007, sub-contractor on PRJ-006): Invoice for Week 2-3 (09-21 Mar): 80 hrs at Rs.2,200/hr = Rs.1,76,000 + GST 18% = Rs.2,07,680. TDS 194C 2% = Rs.3,520. Net payable: Rs.2,04,160. Cross-check hours against project actuals.","accounting":"Dr Sub-contract Expense Rs.1,76,000 + GST Input Rs.31,680 | Cr AP Rs.2,04,160 + TDS Rs.3,520","integrity":"Sub-contractor hours vs invoice"},
    {"id":"T044","date":"18-Mar-26","module":"Timesheets","type":"Utilization Report - Mid-month","priority":"Normal","prompt":"Generate mid-March utilization report: Sneha Joshi: 93%. Amit Rathod: 100%. Rahul Dev: 100%. Divya Mehta: 80%. Kiran Pillai: 90%. Ananya Singh: 100%. BENCH: Meera Das: 50%. Yash Trivedi: 70%. Om Tiwari: 60% (new). Company avg: 82%.","accounting":"Utilization drives revenue realization","integrity":"Utilization vs billing"},
    {"id":"T045","date":"20-Mar-26","module":"Timesheets","type":"Overtime Approval - PRJ-001","priority":"Normal","prompt":"PM Ravi Kapoor requests OT approval for PRJ-001 crunch: Sneha Joshi 6 hrs OT + Amit Rathod 4 hrs OT + Divya Mehta 4 hrs OT. OT hours billable at 1.5x standard rate. MD approval obtained. Total OT billing: Rs.43,050.","accounting":"OT billing: 14 hrs x 1.5 rate - additional revenue Rs.43,050 to PRJ-001","integrity":"OT billing approval"},
    {"id":"T046","date":"23-Mar-26","module":"Timesheets","type":"Weekly Timesheet - Week 4","priority":"Normal","prompt":"Week 4 timesheets (23-28 Mar): Priya Menon: PRJ-005 M4 UAT 32hrs + PRJ-002 8hrs. Sneha Joshi: PRJ-001 32hrs + PRJ-005 final 8hrs. Rahul Dev: PRJ-002 24hrs + PRJ-006 16hrs. Siddharth Roy: PRJ-003 24hrs + PRJ-007 16hrs. Fatima Khan: PRJ-002 16hrs + PRJ-007 24hrs.","accounting":"Week 4 hours feed March monthly billing cycles","integrity":"Timely submission - billing cut-off"},
    {"id":"T047","date":"25-Mar-26","module":"Timesheets","type":"Timesheet - Non-Billable Internal","priority":"Normal","prompt":"Log non-billable hours for March (all employees): RFP prep 20hrs. Tata Digital demo 13hrs. Town hall 40hrs. Compliance training 60hrs. Total non-billable overhead: 133 hrs.","accounting":"Non-billable hours absorbed into SG&A / overhead","integrity":"Non-billable cost tracking"},
    {"id":"T048","date":"26-Mar-26","module":"Timesheets","type":"Timesheet Lock - March Cut-off","priority":"Critical","prompt":"Lock all timesheets for 01-Mar to 28-Mar at 6 PM 28-Mar. After lock: no edits without Finance Manager approval. Reason: March billing cut-off - timesheets feed invoice generation.","accounting":"Timesheet lock triggers billing finalization","integrity":"Month-end cut-off control"},
    {"id":"T049","date":"28-Mar-26","module":"Timesheets","type":"Monthly Hours Consolidation","priority":"Critical","prompt":"Consolidate all March timesheet hours by project: PRJ-001: 520 hrs. PRJ-002: 280 hrs USD 95/hr = USD 26,600. PRJ-003: 280 hrs. PRJ-004: 160 hrs (retainer). PRJ-005: 120 hrs (final month). PRJ-006: Rahul 128 hrs + Om 96 hrs = 224 hrs GBP 140. PRJ-007: 152 hrs.","accounting":"Hours to billing: generate invoices per project billing method","integrity":"Hours-to-revenue bridge"},
    {"id":"T050","date":"29-Mar-26","module":"Timesheets","type":"PRJ-006 Hours - Bi-monthly Billing","priority":"High","prompt":"PRJ-006 RetailCo UK: Bi-monthly billing Feb+Mar. Total hours: Feb (Rahul 120hrs) + Mar (Rahul 128hrs + Om 96hrs) = 344 hrs. Billing: 344 hrs x GBP 140 = GBP 48,160. INR @ Rs.106.80 = Rs.51,41,488. Raise export invoice EXP-INV-2026-011.","accounting":"Dr Export AR GBP 48,160 x 106.80 = Rs.51,41,488 | Cr Export Revenue; IGST nil LUT","integrity":"T&M export billing - hours accumulation"},
    {"id":"T051","date":"30-Mar-26","module":"Timesheets","type":"PRJ-002 March Billing","priority":"High","prompt":"PRJ-002 Mahindra Logistics T&M billing for March: 280 hrs x USD 95 = USD 26,600. INR @ Rs.84.50 = Rs.22,47,700. Raise invoice INV-DOM-2026-038 (IGST 18%). Total invoice: Rs.26,52,286.","accounting":"Dr AR Rs.26,52,286 | Cr Revenue Rs.22,47,700 + GST Rs.4,04,586","integrity":"T&M domestic billing"},
    {"id":"T052","date":"31-Mar-26","module":"Timesheets","type":"PRJ-006 Feb Hours - Accrued Revenue","priority":"Critical","prompt":"PRJ-006 Feb hours (120 hrs x GBP 140 = GBP 16,800) were accrued in Feb. March invoice captures both months. Verify: Feb accrued revenue Rs.17,94,240 correctly reversed and re-recognized through combined invoice. No double counting.","accounting":"Feb accrual: reverse Dr Revenue | Cr Accrued Revenue; Mar invoice captures both months.","integrity":"Accrual reversal - cut-off accuracy"},
    {"id":"T053","date":"31-Mar-26","module":"Timesheets","type":"Billable Utilization - Final March","priority":"Normal","prompt":"Final March utilization: Delivery team (16 billable): Total available: 3,680 hrs. Total billable: 2,320 hrs. Utilization: 63%. Target: 75%. Gap: 12%. Bench impact: Meera Das + Arjun Nath (new) + Om Tiwari (partial). Without bench: 71%.","accounting":"Utilization KPI for management","integrity":"Monthly utilization report"},
    {"id":"T054","date":"31-Mar-26","module":"Timesheets","type":"Timesheet - Project Hours Summary","priority":"Normal","prompt":"March timesheet summary by module: Total logged hours: 4,200. Billable: 2,320 (55.2%). Non-billable delivery: 480 (11.4%). Bench/training: 640 (15.2%). Support staff: 760 (18.1%). Revenue per billable hour: Rs.4,570.","accounting":"Hours to revenue bridge for management reporting","integrity":"Timesheet completeness check"},
    {"id":"T055","date":"02-Mar-26","module":"Buying","type":"PO - Azure Cloud Infra","priority":"High","prompt":"Raise PO to Microsoft India (V001) for March Azure cloud consumption estimate: PRJ-002 (Rs.1,85,000) + PRJ-005 (Rs.51,600) = Rs.2,36,600. Total with GST 18%: Rs.2,79,188. RCM applicable on import of services. Raise PO PO-CLOUD-2026-03.","accounting":"On invoice: Dr Cloud Expense Rs.2,36,600 + GST Input (RCM) Rs.42,588 | Cr AP Rs.2,79,188; RCM: Dr GST Output Rs.42,588 | Cr GST Payable Rs.42,588","integrity":"RCM on imported cloud services"},
    {"id":"T056","date":"03-Mar-26","module":"Buying","type":"PO - AWS Infrastructure","priority":"Normal","prompt":"Raise PO to AWS India (V002) for March Managed Services infra: PRJ-004 (Rs.45,000) + internal CI/CD (Rs.22,000) = Rs.67,000 + GST 18% = Rs.79,060. PO PO-CLOUD-2026-04.","accounting":"Dr Cloud Expense Rs.67,000 + GST Input Rs.12,060 | Cr AP Rs.79,060","integrity":"Cloud cost allocation"},
    {"id":"T057","date":"05-Mar-26","module":"Buying","type":"Annual Renewal - Atlassian","priority":"Normal","prompt":"Atlassian Jira/Confluence annual renewal (V003): Rs.4,80,000 + GST 18% = Rs.5,66,400. RCM applicable. Payment due: immediate. Post as prepaid expense, amortize Rs.40,000/month over 12 months. PO already approved.","accounting":"Dr Prepaid Expense Rs.4,80,000 + GST Input Rs.86,400 | Cr Bank Rs.5,66,400; Monthly: Dr SaaS Expense Rs.40,000 | Cr Prepaid","integrity":"Prepaid amortization - Atlassian"},
    {"id":"T058","date":"06-Mar-26","module":"Buying","type":"Invoice Received - Regus","priority":"Normal","prompt":"Regus (V010) March rent invoice for BLR co-working: Rs.1,20,000 + GST 18% = Rs.1,41,600. TDS 194I @ 10% on Rs.1,20,000 = Rs.12,000. Net payable: Rs.1,29,600. Post invoice, schedule payment 10-Mar.","accounting":"Dr Rent Expense Rs.1,20,000 + GST Input Rs.21,600 | Cr AP Rs.1,29,600 + TDS Payable Rs.12,000","integrity":"Rent TDS - 194I compliance"},
    {"id":"T059","date":"08-Mar-26","module":"Buying","type":"Sub-contractor Invoice - InfoSys","priority":"High","prompt":"InfoSys BPM (V006) invoice for Feb sub-contract work on PRJ-001 (QA augmentation): 120 hrs x Rs.3,000/hr = Rs.3,60,000 + GST 18% = Rs.4,24,800. TDS 194C @ 2% = Rs.7,200. Net payable: Rs.4,17,600.","accounting":"Dr Sub-contract Expense Rs.3,60,000 + GST Input Rs.64,800 | Cr AP Rs.4,17,600 + TDS Rs.7,200","integrity":"Sub-contractor invoice verification"},
    {"id":"T060","date":"10-Mar-26","module":"Buying","type":"Vendor Payment Batch","priority":"Critical","prompt":"Process vendor payment batch: Regus Rs.1,29,600 (NEFT). Salary Feb clearing Rs.3,20,000 (bulk NEFT). TDS Feb remittance Rs.2,83,620 (Challan 281). Total outflow: Rs.7,33,220.","accounting":"Dr AP Rs.1,29,600 + Salary Payable Rs.3,20,000 + TDS Payable Rs.2,83,620 | Cr Bank Rs.7,33,220","integrity":"Vendor payment reconciliation"},
    {"id":"T061","date":"12-Mar-26","module":"Buying","type":"PO - Sub-contractor PRJ-006","priority":"High","prompt":"Raise PO for FreeAgent Devs (V007) for PRJ-006 sub-contract: 2 months estimated 160 hrs x Rs.2,200/hr = Rs.3,52,000 + GST 18% = Rs.4,15,360. TDS 194C @ 2%. PO PO-006-SC-01.","accounting":"Committed cost - post on invoice receipt","integrity":"Sub-contract PO approval"},
    {"id":"T062","date":"14-Mar-26","module":"Buying","type":"Azure Invoice - March","priority":"Normal","prompt":"Microsoft India (V001) Azure invoice received: Rs.2,38,400 (actual > PO by Rs.1,800 - PRJ-002 scaling event). Variance within 5% tolerance. Approve. GST 18% = Rs.42,912. RCM applicable. Net: Rs.2,81,312.","accounting":"Dr Cloud Expense Rs.2,38,400 + GST Input Rs.42,912 | Cr AP Rs.2,81,312; RCM self-assessment","integrity":"PO vs Invoice variance"},
    {"id":"T063","date":"16-Mar-26","module":"Buying","type":"Legal Fee Invoice - Deloitte","priority":"Normal","prompt":"Deloitte India (V008) statutory audit interim billing: Rs.2,50,000 + GST 18% = Rs.2,95,000. TDS 194J @ 10% = Rs.25,000. Net payable: Rs.2,70,000. Post and schedule March-end payment.","accounting":"Dr Audit Fee Rs.2,50,000 + GST Input Rs.45,000 | Cr AP Rs.2,70,000 + TDS Rs.25,000","integrity":"Professional fee TDS"},
    {"id":"T064","date":"18-Mar-26","module":"Buying","type":"Marketing Invoice","priority":"Normal","prompt":"Network18 Media (V009) digital marketing campaign Feb-Mar: Rs.1,80,000 + GST 18% = Rs.2,12,400. TDS 194C @ 2% = Rs.3,600. Allocate: 60% lead gen (Sales), 40% brand (Corporate). Post invoice.","accounting":"Dr Marketing Expense Rs.1,80,000 + GST Input Rs.32,400 | Cr AP Rs.2,08,800 + TDS Rs.3,600","integrity":"Marketing cost allocation"},
    {"id":"T065","date":"20-Mar-26","module":"Buying","type":"Vendor Payment - InfoSys","priority":"High","prompt":"Pay InfoSys BPM (V006) outstanding: Rs.4,17,600 (Feb QA sub-contract). NEFT to InfoSys bank account. Post payment. After payment: verify InfoSys files their GSTR-1 (for our ITC claim in 2A).","accounting":"Dr AP Rs.4,17,600 | Cr Bank Rs.4,17,600","integrity":"Vendor payment + ITC dependency"},
    {"id":"T066","date":"22-Mar-26","module":"Buying","type":"New Laptop Purchase","priority":"Normal","prompt":"Purchase laptop for new hire Arjun Nath: Dell Latitude 7440, Rs.85,000 + GST 18% = Rs.1,00,300. Capitalize as fixed asset. Depreciation SLM 3 years. Tag: FA-LAP-022. Allocate to PRJ-INT (bench assignment). Vendor: direct purchase (not from regular vendor list).","accounting":"Dr Fixed Assets Rs.85,000 + GST Input Rs.15,300 | Cr Bank Rs.1,00,300; Depreciation from Mar: Rs.1,879/month prorated","integrity":"FA capitalization + ITC on capital goods"},
    {"id":"T067","date":"24-Mar-26","module":"Buying","type":"AWS Payment","priority":"Normal","prompt":"Pay AWS India (V002) March invoice Rs.79,060. Direct bank transfer. Post payment.","accounting":"Dr AP Rs.79,060 | Cr Bank Rs.79,060","integrity":"Cloud vendor payment"},
    {"id":"T068","date":"26-Mar-26","module":"Buying","type":"Month-end Accruals - Vendors","priority":"Critical","prompt":"Accrue unbilled vendor costs for March: FreeAgent Devs (V007) March hours Rs.1,76,000 + GST Rs.31,680 = Rs.2,07,680. Zoho renewal proration Rs.40,000. Marketing accrual Rs.15,000. Total accruals: Rs.2,62,680.","accounting":"Dr Expense accounts Rs.2,31,000 + GST Input Rs.31,680 | Cr Accrued AP Rs.2,62,680","integrity":"Vendor accrual - month-end cut-off"},
    {"id":"T069","date":"28-Mar-26","module":"Buying","type":"TDS Remittance - March","priority":"Critical","prompt":"Remit March TDS deductions: 194J: Rs.25,000 (Deloitte) + Rs.12,000 (V003+V004 RCM proxy). 194C: Rs.7,200 (InfoSys) + Rs.3,520 (FreeAgent) + Rs.3,600 (Network18) = Rs.14,320. 194I: Rs.12,000 (Regus). Total: Rs.63,320. Challan 281. Due: 07-Apr. Pay by 28-Mar (early).","accounting":"Dr TDS Payable Rs.63,320 | Cr Bank Rs.63,320","integrity":"TDS remittance - challan reconciliation"},
    {"id":"T070","date":"31-Mar-26","module":"Buying","type":"AP Aging Review","priority":"Normal","prompt":"AP aging as at 31-Mar: 0-30 days: Rs.8,40,000 (Azure + Deloitte + marketing). 30-60: Rs.0. 60-90: Rs.0. >90: Rs.0. All current. Total AP: Rs.8,40,000. No overdue. Cash position comfortable for settlement.","accounting":"AP aging clean - all within terms","integrity":"Vendor payment compliance"},
    {"id":"T071","date":"01-Mar-26","module":"Selling","type":"Retainer Invoice - Havells","priority":"High","prompt":"Raise March retainer invoice to Havells India (C004): Rs.4,50,000 + IGST 18% (inter-state Gujarat to UP) = Rs.81,000. Total: Rs.5,31,000. Invoice INV-DOM-2026-030. Payment terms: prepaid (due immediately). TDS expected: 194J 10% on Rs.4,50,000 = Rs.45,000. Net receivable: Rs.4,86,000.","accounting":"Dr AR Rs.5,31,000 | Cr Revenue Rs.4,50,000 + IGST Output Rs.81,000; TDS receivable Rs.45,000 on receipt","integrity":"Retainer billing - inter-state GST"},
    {"id":"T072","date":"03-Mar-26","module":"Selling","type":"Collection - Havells Retainer","priority":"Normal","prompt":"Received Havells March retainer payment: Rs.4,86,000 (net of TDS Rs.45,000). Bank credit: HDFC Bank. Post receipt. Update AR. Havells deducted TDS 194J Rs.45,000 - log TDS receivable.","accounting":"Dr Bank Rs.4,86,000 + Dr TDS Receivable Rs.45,000 | Cr AR Rs.5,31,000","integrity":"Collection + TDS receivable"},
    {"id":"T073","date":"07-Mar-26","module":"Selling","type":"Invoice - PRJ-003 M2","priority":"Critical","prompt":"Raise invoice INV-DOM-2026-031 for HDFC AMC (C003) PRJ-003 M2: Rs.7,00,000 + CGST 9% Rs.63,000 + SGST 9% Rs.63,000 = Rs.8,26,000. M2 acceptance certificate AC-003-M2 attached. Payment terms: Net 30. TDS expected: Rs.70,000.","accounting":"Dr AR Rs.8,26,000 | Cr Revenue Rs.7,00,000 + CGST Rs.63,000 + SGST Rs.63,000","integrity":"Milestone invoice - intra-state GST"},
    {"id":"T074","date":"10-Mar-26","module":"Selling","type":"Invoice - PRJ-001 M3","priority":"Critical","prompt":"Raise invoice INV-DOM-2026-033 for Axis Securities (C001) PRJ-001 M3 (Payment Gateway): Rs.13,50,000 + GST 18% (MH to MH = CGST+SGST) = Rs.15,93,000. Acceptance cert attached. TDS expected: Rs.1,35,000.","accounting":"Dr AR Rs.15,93,000 | Cr Revenue Rs.13,50,000 + CGST Rs.1,21,500 + SGST Rs.1,21,500","integrity":"M3 billing + POC revenue alignment"},
    {"id":"T075","date":"12-Mar-26","module":"Selling","type":"Collection - Axis M2","priority":"Normal","prompt":"Received Axis Securities payment for M2 invoice (INV-DOM-2026-028, raised Feb): Rs.12,85,200 (net of TDS Rs.1,35,000). Bank: HDFC. Post receipt. Clear AR. Log TDS receivable.","accounting":"Dr Bank Rs.12,85,200 + Dr TDS Receivable Rs.1,35,000 | Cr AR Rs.14,20,200","integrity":"AR clearing + TDS"},
    {"id":"T076","date":"14-Mar-26","module":"Selling","type":"Credit Note - Havells SLA","priority":"Normal","prompt":"Issue credit note CN-2026-007 to Havells (C004) for SLA breach (March uptime 99.2% vs 99.5% SLA): Rs.1,350 + IGST reversal Rs.243 = Rs.1,593. Adjust against next month invoice.","accounting":"Dr Revenue Rs.1,350 + IGST Output Rs.243 | Cr AR Rs.1,593","integrity":"SLA penalty credit note"},
    {"id":"T077","date":"18-Mar-26","module":"Selling","type":"Export Invoice - PRJ-005 M4","priority":"Critical","prompt":"Raise export invoice EXP-INV-2026-009 for TechFin Corp (C005): USD 30,000 @ Rs.84.50 = Rs.25,35,000. Under LUT - IGST nil. Zero-rated export of services. SOFTEX filing required. Payment terms: Net 15.","accounting":"Dr Export AR Rs.25,35,000 | Cr Export Revenue Rs.25,35,000; IGST nil (LUT)","integrity":"Export invoice - LUT/STPI"},
    {"id":"T078","date":"20-Mar-26","module":"Selling","type":"Collection - HDFC AMC","priority":"Normal","prompt":"Received HDFC AMC payment for M1 invoice (INV-DOM-2026-025, raised Jan): Rs.7,56,000 (net of TDS Rs.70,000). Bank: HDFC. Post. AR cleared.","accounting":"Dr Bank Rs.7,56,000 + Dr TDS Receivable Rs.70,000 | Cr AR Rs.8,26,000","integrity":"AR clearing"},
    {"id":"T079","date":"22-Mar-26","module":"Selling","type":"Invoice - PRJ-002 March T&M","priority":"High","prompt":"Raise invoice INV-DOM-2026-041 to Mahindra Logistics (C002): USD 26,600 @ Rs.84.50 = Rs.22,47,700 + CGST+SGST 18% = Rs.26,52,286. Timesheet backup attached (280 hrs). Payment terms: Net 30.","accounting":"Dr AR Rs.26,52,286 | Cr T&M Revenue Rs.22,47,700 + GST Rs.4,04,586","integrity":"T&M invoice with timesheet proof"},
    {"id":"T080","date":"24-Mar-26","module":"Selling","type":"Collection - TechFin Export","priority":"High","prompt":"Received TechFin Corp USD 30,000 via SWIFT to EEFC account. Conversion: retain in EEFC. Book rate: Rs.84.50. Bank credit rate: Rs.84.60 (spot). Forex gain: USD 30,000 x Rs.0.10 = Rs.3,000. Post receipt.","accounting":"Dr EEFC Bank Rs.25,38,000 | Cr Export AR Rs.25,35,000 + Forex Gain Rs.3,000","integrity":"Export collection + FEMA compliance"},
    {"id":"T081","date":"25-Mar-26","module":"Selling","type":"Export Invoice - PRJ-006 Bi-monthly","priority":"Critical","prompt":"Raise export invoice EXP-INV-2026-011 for RetailCo PLC (C006): GBP 48,160 @ Rs.106.80 = Rs.51,41,488. Under LUT - IGST nil. Feb+Mar combined (344 hrs). Timesheet backup + FreeAgent sub-hours excluded from billing.","accounting":"Dr Export AR Rs.51,41,488 | Cr Export Revenue Rs.51,41,488; IGST nil LUT","integrity":"Bi-monthly export invoice"},
    {"id":"T082","date":"26-Mar-26","module":"Selling","type":"Collection - RetailCo Partial","priority":"Normal","prompt":"Received RetailCo PLC GBP 24,640 (partial payment for Jan-Feb invoice EXP-INV-2026-008). SWIFT to Axis Bank. Converted at Rs.107.10. Book rate Rs.106.80. Forex gain: GBP 24,640 x Rs.0.30 = Rs.7,392.","accounting":"Dr Bank Rs.26,38,944 (INR) | Cr Export AR Rs.26,31,552 + Forex Gain Rs.7,392","integrity":"Partial export collection"},
    {"id":"T083","date":"27-Mar-26","module":"Selling","type":"Invoice - PRJ-007 M1 Accrual","priority":"Critical","prompt":"PRJ-007 Asian Paints M1 accepted 25-Mar but invoice NOT raised (AP team unavailable). Revenue recognized Rs.6,00,000. Post as Unbilled AR: Rs.6,00,000 + GST Rs.1,08,000 = Rs.7,08,000. Invoice to be raised 03-Apr.","accounting":"Dr Unbilled AR Rs.7,08,000 | Cr Revenue Rs.6,00,000 + GST Payable Rs.1,08,000","integrity":"Accrued revenue - FY-end unbilled"},
    {"id":"T084","date":"28-Mar-26","module":"Selling","type":"AR Aging Report","priority":"Normal","prompt":"AR aging as at 28-Mar: 0-30 days: Rs.58,30,000. 30-60: Rs.8,26,000 (HDFC M2 - paid 20-Mar actually). 60-90: Rs.0. >90: Rs.0. Total billed AR: Rs.66,56,000. Unbilled AR: Rs.7,08,000. Grand total: Rs.73,64,000. All current - healthy AR.","accounting":"AR aging report for management","integrity":"Receivable health check"},
    {"id":"T085","date":"31-Mar-26","module":"Selling","type":"Revenue Summary - March","priority":"Critical","prompt":"March 2026 revenue summary: Domestic: PRJ-001 Rs.7,20,000 + PRJ-003 Rs.7,00,000 + PRJ-004 Rs.4,50,000 + PRJ-002 Rs.22,47,700 + PRJ-007 Rs.6,00,000 = Rs.47,17,700. Export: PRJ-005 Rs.25,35,000 + PRJ-006 Rs.33,49,248 = Rs.58,84,248. Grand total: Rs.1,06,01,948.","accounting":"Revenue recognized per Ind AS 115","integrity":"Revenue completeness assertion"},
    {"id":"T086","date":"01-Mar-26","module":"HR","type":"New Hire Onboarding","priority":"High","prompt":"Onboard new hire: Arjun Nath (E021), Software Engineer, Engineering dept. CTC: Rs.78,000/month. Bill rate: USD 48/hr. Location: Ahmedabad. Joining: 04-Mar-26. Laptop procurement (Rs.85,000). BGV pending. Assign to PRJ-INT (bench) until project allocation.","accounting":"Onboarding cost: laptop Rs.85,000 (FA) + induction materials Rs.5,000 (SG&A)","integrity":"New employee setup"},
    {"id":"T087","date":"03-Mar-26","module":"HR","type":"Attendance Import","priority":"Normal","prompt":"Import March attendance from biometric system: 23 working days in March 2026. Ahmedabad office: 15 employees present. Bengaluru: 6 employees. Holiday: Holi 14-Mar (Ahmedabad only). Mark all employees attendance. Flag: Fatima Khan absent 10-11 Mar without leave applied.","accounting":"Attendance feeds payroll - LWP deduction for Fatima Khan","integrity":"Attendance - payroll link"},
    {"id":"T088","date":"05-Mar-26","module":"HR","type":"Leave Application - Divya Mehta","priority":"Normal","prompt":"Divya Mehta (E011) applies Sick Leave for 06-Mar (1 day). Reason: fever. Medical certificate uploaded. Manager Ravi Kapoor approves. Deduct from SL balance (12 SL/year, 8 remaining). No salary deduction.","accounting":"SL does not impact salary - no deduction","integrity":"Leave balance tracking"},
    {"id":"T089","date":"06-Mar-26","module":"HR","type":"Variable Pay Approval","priority":"High","prompt":"MD Harsh Mehra approves Q3 FY26 variable pay: Vikram Jain (Sales): Rs.62,500 (target achieved 125% of quarterly quota). Ravi Kapoor (Delivery): Rs.55,500 (project delivery on-time bonus). Include in March payroll. Total variable: Rs.1,18,000.","accounting":"Dr Variable Pay Expense Rs.1,18,000 | Cr Salary Payable Rs.1,18,000","integrity":"Variable pay computation"},
    {"id":"T090","date":"08-Mar-26","module":"HR","type":"TDS Salary - Monthly","priority":"Critical","prompt":"Compute monthly TDS for March payroll (20 employees, regime-based): Total estimated TDS deduction: Rs.1,62,000. Higher deductions for Harsh Mehra (Rs.45,000), Ravi Kapoor (Rs.22,000), Priya Menon (Rs.18,000). Post TDS payable.","accounting":"Dr Salary Payable Rs.1,62,000 | Cr TDS Payable (24Q) Rs.1,62,000","integrity":"TDS on salary - monthly computation"},
    {"id":"T091","date":"10-Mar-26","module":"HR","type":"Training Request","priority":"Normal","prompt":"Om Tiwari (E016) requests AWS Solutions Architect certification course: Rs.35,000. Manager Ravi Kapoor approves. Policy: company bears 80% if certified within 6 months. Advance Rs.28,000. Post to training budget. Allocate to PRJ-006 team development.","accounting":"Dr Training Expense Rs.28,000 | Cr Bank Rs.28,000; Balance on certification","integrity":"Training cost - project allocation"},
    {"id":"T092","date":"12-Mar-26","module":"HR","type":"LWP - Unauthorized Absence","priority":"Normal","prompt":"Fatima Khan (E013) absent 10-11 Mar (2 days) without approved leave. Manager marks as LWP. Salary deduction: Rs.76,000 / 23 days x 2 = Rs.6,609. Record disciplinary note. Adjust in March payroll.","accounting":"LWP deduction Rs.6,609 reduces net salary","integrity":"LWP - payroll deduction"},
    {"id":"T093","date":"14-Mar-26","module":"HR","type":"Promotion - Mid-year","priority":"Normal","prompt":"Yash Trivedi (E015) promoted from Mobile Developer to Sr. Mobile Developer effective 01-Mar (backdated). CTC revised: Rs.85,000 to Rs.1,05,000/month (+23.5%). Arrears for March: Rs.20,000. Bill rate updated: Rs.52 to Rs.62/hr.","accounting":"Dr Salary Expense Rs.20,000 (arrear) | Cr Salary Payable Rs.20,000","integrity":"Backdated salary revision"},
    {"id":"T094","date":"15-Mar-26","module":"HR","type":"Employee Advance","priority":"Normal","prompt":"Sneha Joshi (E005) requests salary advance Rs.30,000 (medical emergency). Approved by MD. Policy: max 1 month CTC, repay over 3 months. Deduct Rs.10,000/month from April-June.","accounting":"Dr Employee Advance Rs.30,000 | Cr Bank Rs.30,000","integrity":"Salary advance - recovery schedule"},
    {"id":"T095","date":"16-Mar-26","module":"HR","type":"Resignation - Notice Period","priority":"High","prompt":"Siddharth Roy (E010, Sr. Data Engineer) resigns. LWD: 30-Apr (45-day notice). Serves notice fully. Handing over PRJ-003 and PRJ-007 to Ananya Singh. PRJ-007 M2 depends on Siddharth - succession plan critical.","accounting":"No immediate accounting. F&F in April.","integrity":"Attrition - project risk"},
    {"id":"T096","date":"18-Mar-26","module":"HR","type":"Payroll - Variable Pay Processing","priority":"Normal","prompt":"Include variable pay in March payroll: Vikram Jain Rs.62,500 + Ravi Kapoor Rs.55,500 + Yash Trivedi arrear Rs.20,000 + Sneha Joshi advance Rs.30,000 (to deduct). Gross variable additions: Rs.1,38,000.","accounting":"Variable components updated in payroll input","integrity":"Payroll input accuracy"},
    {"id":"T097","date":"20-Mar-26","module":"HR","type":"Reimbursement - Travel Claims","priority":"Normal","prompt":"Process travel reimbursements for March: Vikram Jain Rs.18,500. Harsh Mehra Rs.32,000. Ravi Kapoor Rs.12,000. Total claims: Rs.62,500. All within policy.","accounting":"Dr Travel & Conveyance Rs.62,500 | Cr Bank Rs.62,500","integrity":"T&E policy compliance"},
    {"id":"T098","date":"22-Mar-26","module":"HR","type":"ESOP Vesting","priority":"Normal","prompt":"ESOP vesting event: 5 employees reach 2-year cliff (vest 25% of granted options): Sneha Joshi 2,500, Rahul Dev 3,000, Ananya Singh 2,000, Priya Menon 4,000, Kiran Pillai 1,500. Exercise price: Rs.100/share. Fair value at grant: Rs.180/share. Post ESOP expense.","accounting":"Dr ESOP Compensation Expense | Cr ESOP Reserve (Equity). Ind AS 102.","integrity":"ESOP accounting - Ind AS 102"},
    {"id":"T099","date":"25-Mar-26","module":"HR","type":"PF Return - Feb","priority":"Critical","prompt":"File PF ECR for February on EPFO portal. Employee PF 12% of basic (17 eligible). Employer PF 12% + admin 0.5% + EDLI 0.5% = 13%. Total challan: Rs.1,91,250. Filing 25-Mar (10 days late). Penalty assess.","accounting":"Dr PF Payable Rs.1,91,250 + Late fee Rs.500 | Cr Bank Rs.1,91,750","integrity":"PF late filing - EPFO compliance"},
    {"id":"T100","date":"28-Mar-26","module":"HR","type":"Gratuity Provision","priority":"Normal","prompt":"Post gratuity provision for March (Ind AS 19): Employees >5 years: Ravi Kapoor, Priya Menon, Pooja Sharma. Incremental liability: Rs.32,500. Siddharth Roy (resigned, 3.5 years) - not eligible.","accounting":"Dr Gratuity Expense Rs.32,500 | Cr Gratuity Provision Rs.32,500","integrity":"Ind AS 19 - post-employment benefit"},
    {"id":"T101","date":"31-Mar-26","module":"HR","type":"Payroll Processing - March","priority":"Critical","prompt":"Process March 2026 payroll for 21 employees: Total Gross: ~Rs.18,50,000. Deductions: PF, TDS, LWP Fatima Rs.6,609, Advance Sneha Rs.30,000. Variable additions: Rs.1,38,000. Arrear Yash Rs.20,000. Employer PF Rs.99,450. Post payroll journal.","accounting":"Dr Gross Salary Rs.18,50,000 + Employer PF Rs.99,450 + ESOP | Cr Net Pay + PF + TDS + Payables","integrity":"Full payroll computation"},
    {"id":"T102","date":"31-Mar-26","module":"HR","type":"Salary Disbursement","priority":"Critical","prompt":"Disburse March net salaries to all 21 employees. Net pay after deductions: ~Rs.15,80,000. Ahmedabad (15): ICICI bulk transfer. Bengaluru (6): Axis Bank NEFT. Payslips generated.","accounting":"Dr Salary Payable Rs.15,80,000 | Cr Bank Rs.15,80,000","integrity":"Payroll disbursement"},
    {"id":"T103","date":"31-Mar-26","module":"HR","type":"Leave Liability Provision","priority":"Normal","prompt":"Year-end leave liability: Total unutilized leave: 385 days. Encashment liability: Rs.4,20,000. Post provision per Ind AS 19 (short-term employee benefit).","accounting":"Dr Leave Encashment Expense Rs.4,20,000 | Cr Leave Encashment Provision Rs.4,20,000","integrity":"Ind AS 19 - leave encashment liability"},
    {"id":"T104","date":"31-Mar-26","module":"HR","type":"Headcount Summary","priority":"Normal","prompt":"FY-end headcount: Opening 01-Apr-25: 16. Additions FY26: 5 (including Arjun Nath March). Attrition FY26: 1 (Siddharth Roy, exits April). Closing: 21. Billable: 16. Non-billable: 5. Bench: 2. Attrition rate: 6.25%.","accounting":"No entry - HR analytics","integrity":"Headcount reconciliation"},
    {"id":"T105","date":"31-Mar-26","module":"HR","type":"FY26 Increment Letters","priority":"Normal","prompt":"Issue FY26 increment letters effective 01-Apr-2026 for all 20 active employees. Average increment: 12% performers, 8% meets. High performers: Sneha Joshi +18%, Rahul Dev +15%, Ananya Singh +14%. New CTC master updated for April.","accounting":"No March entry - effective April","integrity":"Salary revision workflow"},
    {"id":"T106","date":"01-Mar-26","module":"Accounting","type":"Opening Balances","priority":"Critical","prompt":"Post opening trial balance as at 01-Mar-26. Total Debits: Rs.2,81,42,000. Total Credits: Rs.2,81,42,000. TB balanced. Contract Asset Rs.24,10,000 + Deferred Revenue Rs.18,40,000 = Ind AS 115 B/S items.","accounting":"Opening TB must balance - Total Dr = Total Cr","integrity":"Opening balance verification"},
    {"id":"T107","date":"02-Mar-26","module":"Accounting","type":"GST Payment - Feb","priority":"Critical","prompt":"Pay February net GST liability: Output CGST Rs.4,10,000 + SGST Rs.4,10,000. ITC offset: CGST Rs.1,85,000 + SGST Rs.1,85,000. Net cash: Rs.4,50,000. Challan PMT-06.","accounting":"Dr GST Payable Rs.4,50,000 | Cr Bank Rs.4,50,000","integrity":"GST cash payment"},
    {"id":"T108","date":"03-Mar-26","module":"Accounting","type":"Bank Reconciliation - HDFC","priority":"High","prompt":"HDFC Bank recon as at 03-Mar: Book Rs.68,40,000. Bank Rs.69,22,000. Differences: (1) Client NEFT Rs.82,000 not in books. (2) Bank charges Rs.1,200 not booked. (3) Interest Rs.3,800.","accounting":"Dr Bank Rs.85,800 | Cr Income Rs.85,800; Dr Bank charges Rs.1,200 | Cr Bank","integrity":"Bank recon - mystery credit"},
    {"id":"T109","date":"05-Mar-26","module":"Accounting","type":"Advance Tax - Q4 Payment","priority":"Critical","prompt":"Pay Q4 advance tax: Rs.10,00,000. Total FY26 paid: Rs.28,00,000. Note: STPI exports exempt u/s 10AA reduces taxable income significantly.","accounting":"Dr Advance Tax Rs.10,00,000 | Cr Bank Rs.10,00,000","integrity":"Advance tax - 10AA exemption impact"},
    {"id":"T110","date":"07-Mar-26","module":"Accounting","type":"Revenue Accrual Reversal - PRJ-002 Feb","priority":"Critical","prompt":"Reverse February PRJ-002 accrued revenue: Rs.23,92,195 (298 hrs x USD 95 x Rs.84.50). Invoice raised in March covers same period. Reverse accrual then post invoice. Net: no double counting.","accounting":"Accrual reversal: Dr Revenue | Cr Unbilled AR; then invoice posting","integrity":"Accrual reversal - standard practice"},
    {"id":"T111","date":"10-Mar-26","module":"Accounting","type":"EEFC Account Management","priority":"Normal","prompt":"EEFC: Opening USD 36,000. Receipt: TechFin USD 30,000. Total USD 66,000. Convert 50%: USD 33,000 x Rs.84.60 = Rs.27,91,800. Retain USD 33,000. Forex gain: Rs.3,300.","accounting":"Dr Bank INR Rs.27,91,800 | Cr EEFC Rs.27,88,500 + Forex Gain Rs.3,300","integrity":"EEFC management - RBI regulations"},
    {"id":"T112","date":"12-Mar-26","module":"Accounting","type":"Loan - Working Capital","priority":"Normal","prompt":"Draw down WC loan from ICICI: Rs.40,00,000 from CC limit. Purpose: bridge payroll + vendor payments. Interest: 10.75% p.a. daily.","accounting":"Dr Bank Rs.40,00,000 | Cr CC Loan Rs.40,00,000","integrity":"Working capital bridge"},
    {"id":"T113","date":"14-Mar-26","module":"Accounting","type":"CC Loan Repayment","priority":"Normal","prompt":"Repay WC CC loan: Rs.40,00,000. Interest for 2 days: Rs.2,356. Post repayment + interest.","accounting":"Dr CC Loan Rs.40,00,000 + Dr Interest Rs.2,356 | Cr Bank Rs.40,02,356","integrity":"WC loan - interest calc"},
    {"id":"T114","date":"15-Mar-26","module":"Accounting","type":"Depreciation","priority":"High","prompt":"Post March depreciation: Laptops Rs.40,833/month. Office equipment Rs.8,888/month. Furniture Rs.7,500/month. New laptop prorated: Rs.1,879/month. ROU Amortization Rs.55,000. Total: Rs.1,14,100.","accounting":"Dr Depreciation Rs.59,100 + Dr ROU Amort Rs.55,000 | Cr Acc Dep + ROU Asset","integrity":"Depreciation schedule"},
    {"id":"T115","date":"18-Mar-26","module":"Accounting","type":"GST ITC Reconciliation","priority":"Critical","prompt":"Reconcile ITC: GSTR-2A vs books. Mismatch: InfoSys BPM invoice Rs.4,24,800 - InfoSys has not filed GSTR-1 for Feb. ITC claim blocked: Rs.64,800. Rule 36(4). Flag to InfoSys.","accounting":"ITC temporarily blocked Rs.64,800 - reclassify to Blocked ITC","integrity":"GSTR-2A mismatch - ITC blocking"},
    {"id":"T116","date":"20-Mar-26","module":"Accounting","type":"Foreign Currency Revaluation","priority":"Normal","prompt":"Mid-month forex: GBP moved from Rs.106.80 to Rs.107.10. Revalue RetailCo AR GBP 49,280. MTM gain: Rs.16,784. USD stable.","accounting":"Dr AR Rs.16,784 | Cr Unrealized Forex Gain Rs.16,784","integrity":"Mid-month MTM revaluation"},
    {"id":"T117","date":"22-Mar-26","module":"Accounting","type":"Accrual - Sub-contractor March","priority":"Normal","prompt":"Accrue FreeAgent Devs March hours: 80 hrs x Rs.2,200 = Rs.1,76,000 + GST Rs.31,680. Invoice expected 05-Apr. Accrue in March P&L.","accounting":"Dr Sub-contract Expense Rs.1,76,000 + GST Input Rs.31,680 | Cr Accrued AP Rs.2,07,680","integrity":"Sub-contractor accrual - cut-off"},
    {"id":"T118","date":"24-Mar-26","module":"Accounting","type":"Provision - Bad Debt Review","priority":"Normal","prompt":"Review AR for bad debt: All current, no overdue >60 days. No provision needed. Monitor Mahindra large USD balance. Policy: 0% <=60 days, 25% 61-90, 50% 91-180, 100% >180.","accounting":"No new provision - document review","integrity":"Credit risk review"},
    {"id":"T119","date":"25-Mar-26","module":"Accounting","type":"Advance Tax Computation Review","priority":"High","prompt":"Review advance tax FY26: Paid Rs.28,00,000. Revised taxable income ~Rs.52,00,000 (after STPI exempt). Tax @ 25.17%: Rs.13,08,840. Excess: Rs.14,91,160 refund expected.","accounting":"Excess advance tax = Tax Asset Rs.14,91,160","integrity":"STPI + 80JJAA tax benefits"},
    {"id":"T120","date":"26-Mar-26","module":"Accounting","type":"STPI Compliance - Softex Filing","priority":"Critical","prompt":"File SOFTEX forms for March export invoices: PRJ-005 (USD 30,000) and PRJ-006 (GBP 49,280). Mandatory for IT services exports >USD 25,000. Submit to STPI Ahmedabad. BRC to be filed within 9 months.","accounting":"No accounting - FEMA/STPI compliance","integrity":"STPI/SOFTEX - export compliance"},
    {"id":"T121","date":"27-Mar-26","module":"Accounting","type":"Transfer Pricing Note","priority":"Normal","prompt":"Assess TP: PRJ-005 and PRJ-006 are arm's length with unrelated parties. No TP adjustment needed. Rates benchmarked against NASSCOM surveys. TP not applicable currently.","accounting":"No entry - TP documentation","integrity":"Transfer pricing compliance"},
    {"id":"T122","date":"28-Mar-26","module":"Accounting","type":"Forex MTM - FY-end","priority":"Critical","prompt":"Year-end forex revaluation at RBI rate (Rs.84.80/USD, Rs.107.15/GBP): EEFC USD 33,000 gain Rs.9,900. RetailCo AR GBP 24,640 gain Rs.1,132. Total unrealized gain: Rs.11,032. Post MTM. Ind AS 21.","accounting":"Dr EEFC + AR | Cr Unrealized Forex Gain Rs.11,032","integrity":"Ind AS 21 - FY-end MTM"},
    {"id":"T123","date":"29-Mar-26","module":"Accounting","type":"Deferred Tax Computation","priority":"High","prompt":"FY-end deferred tax: Depreciation timing diff Rs.29,550 -> DTL Rs.7,440. Leave provision DTA Rs.1,05,714. ESOP DTA Rs.X. Net DTA movement: post. Apply STPI-exempt impact.","accounting":"Dr/Cr DTA/DTL per computation; Ind AS 12","integrity":"Deferred tax - Ind AS 12"},
    {"id":"T124","date":"29-Mar-26","module":"Accounting","type":"Revenue Recognition Policy Review","priority":"Critical","prompt":"Verify Ind AS 115 compliance: PRJ-001 POC cost-to-cost. PRJ-004 retainer straight-line. PRJ-007 unbilled AR. PRJ-001 deferred revenue. Export under LUT. Sign-off: Nisha Agarwal + Statutory Auditor.","accounting":"Revenue policy sign-off - Ind AS 115 assertion","integrity":"Revenue recognition compliance"},
    {"id":"T125","date":"30-Mar-26","module":"Accounting","type":"Provision - Warranty/SLA","priority":"Normal","prompt":"SLA penalty exposure: PRJ-004 Havells uptime 99.2% vs 99.5%. Penalty: Rs.1,350. Accrue.","accounting":"Dr SLA Penalty Rs.1,350 | Cr Accrued Liabilities Rs.1,350","integrity":"SLA penalty accrual"},
    {"id":"T126","date":"30-Mar-26","module":"Accounting","type":"Trial Balance - Pre-close","priority":"Critical","prompt":"Generate pre-close trial balance for March 2026. Verify revenue accounts, unbilled AR Rs.7,60,000, deferred revenue Rs.9,90,000, TDS receivable Rs.3,99,220. DR = CR.","accounting":"Pre-close TB - all mismatches to be resolved","integrity":"TB control - pre-close"},
    {"id":"T127","date":"31-Mar-26","module":"Accounting","type":"Income Tax Provision","priority":"Critical","prompt":"FY26 income tax provision: PBT Rs.85,00,000. STPI exempt: ~Rs.1,54,89,248 (export revenue). Tax on residual @ 25.17%. Plus MAT check @ 15%. Advance tax Rs.28,00,000 - excess refundable.","accounting":"Dr Tax Expense | Cr Provision for Tax. Excess = TDS Refund Receivable.","integrity":"STPI - 10AA tax holiday benefit"},
    {"id":"T128","date":"31-Mar-26","module":"Accounting","type":"Depreciation - Full Month","priority":"Normal","prompt":"Post final March depreciation: Total tech assets Rs.42,712 + furniture Rs.7,500 + ROU Rs.55,000 = Rs.1,05,212. Update fixed asset register.","accounting":"Dr Depreciation Rs.50,212 + Dr ROU Amort Rs.55,000 | Cr Acc Dep + ROU","integrity":"Full month depreciation"},
    {"id":"T129","date":"31-Mar-26","module":"Accounting","type":"Closing Entries","priority":"Critical","prompt":"Post closing entries: Revenue Rs.1,06,01,948. Employee costs Rs.19,68,000. Sub-contractor Rs.5,36,000. Cloud/infra Rs.4,03,600. SG&A Rs.4,22,500. Depreciation Rs.1,05,212. Interest Rs.2,356. EBITDA Rs.77,17,348. Transfer to retained earnings.","accounting":"P&L accounts zeroed to RE. B/S equity increases by PAT.","integrity":"Month/FY-end close"},
    {"id":"T130","date":"31-Mar-26","module":"Accounting","type":"Balance Sheet - FY-end","priority":"Critical","prompt":"Generate FY-end Balance Sheet as at 31-Mar-2026. Verify cash, AR + Unbilled AR, Deferred Revenue Rs.9,90,000, TDS Receivable, ROU + Lease Liability, Retained Earnings. Assets = Liabilities + Equity.","accounting":"B/S validation - Ind AS presentation","integrity":"FY-end balance sheet proof"},
    {"id":"T131","date":"31-Mar-26","module":"Reports","type":"P&L Statement","priority":"Critical","prompt":"Generate P&L for March 2026 and FY 2025-26: Revenue Rs.1,06,01,948. Revenue split: Domestic Rs.47,17,700, Export Rs.58,84,248. Cost of revenue. Gross Profit. EBITDA. Tax (post STPI benefit). PAT.","accounting":"P&L accuracy and segment disclosure","integrity":"P&L completeness"},
    {"id":"T132","date":"31-Mar-26","module":"Reports","type":"Revenue Recognition Report","priority":"Critical","prompt":"Ind AS 115 Revenue Disclosure: Disaggregation by contract type, geography, currency. Contract assets (unbilled AR). Contract liabilities (deferred revenue). RPO = backlog. Significant judgments: POC method, variable consideration.","accounting":"Ind AS 115 Note to accounts","integrity":"Revenue disclosure completeness"},
    {"id":"T133","date":"31-Mar-26","module":"Reports","type":"Cash Flow Statement","priority":"High","prompt":"Cash Flow (Indirect Method): Operating: PAT + Depreciation + WC changes. Investing: Laptop Rs.85,000 outflow. Financing: WC drawdown/repayment net zero. Net cash change = Closing bank - Opening bank.","accounting":"Ind AS 7 - cash flow reconciliation","integrity":"Cash flow proof"},
    {"id":"T134","date":"31-Mar-26","module":"Reports","type":"Project Profitability Report","priority":"High","prompt":"Project P&L March 2026: PRJ-001: Margin -Rs.1,44,000 (thin). PRJ-002: Rs.15,31,100 (strong). PRJ-006: Rs.27,93,248 (export premium). PRJ-004: Rs.2,70,000. Rank by contribution margin.","accounting":"Management accounting - project profitability","integrity":"Project margin accuracy"},
    {"id":"T135","date":"31-Mar-26","module":"Reports","type":"Backlog / RPO Report","priority":"Normal","prompt":"RPO as at 31-Mar-26: PRJ-001 Rs.5,40,000. PRJ-003 Rs.14,00,000. PRJ-004 Rs.54,00,000. PRJ-007 Rs.12,00,000. Total locked backlog: ~Rs.1,20,00,000. Ind AS 115 para 120 disclosure.","accounting":"RPO disclosure - Ind AS 115 para 120","integrity":"Backlog visibility"},
    {"id":"T136","date":"31-Mar-26","module":"Reports","type":"GSTR-3B Filing","priority":"Critical","prompt":"File GSTR-3B for March 2026: Output GST domestic. Export zero-rated under LUT. RCM payable Rs.2,03,434. ITC available. ITC blocked Rs.64,800 (InfoSys). Net GST cash liability. File by 20-Apr.","accounting":"GST 3B - net cash liability computed","integrity":"GST compliance FY-end"},
    {"id":"T137","date":"31-Mar-26","module":"Reports","type":"Utilization & Margin Dashboard","priority":"Normal","prompt":"Management KPI Dashboard March 2026: Revenue per employee Rs.5,04,854/month. Export T&M GM ~83%. Domestic FP ~40%. Retainer ~60%. Blended GM: ~62%. EBITDA: ~73%. Utilization: 63%. Onsite:Offshore ratio.","accounting":"Management KPI reporting","integrity":"KPI accuracy"},
    {"id":"T138","date":"31-Mar-26","module":"Reports","type":"TDS Return - Q4","priority":"Critical","prompt":"File TDS return Form 24Q + 26Q for Q4 FY26. Verify deductions match challans. Generate Form 16 data. TAN AHDN12345E. Cross-check Form 26AS. File before 31-May.","accounting":"TDS return compliance - Form 24Q + 26Q","integrity":"TDS compliance FY-end"},
    {"id":"T139","date":"31-Mar-26","module":"Reports","type":"FY-end Audit Readiness","priority":"Critical","prompt":"Audit readiness checklist: Bank recons done. AR confirmed. Ind AS 115 revenue. Vendor invoices booked. Depreciation updated. Provisions: gratuity, leave, ESOP, SLA. Forex MTM done. Deferred tax calculated. STPI compliance. TDS filed. TB balanced. B/S + P&L finalized. Sign: Nisha Agarwal + Harsh Mehra.","accounting":"FY close certification","integrity":"Complete audit readiness"},
    {"id":"T140","date":"31-Mar-26","module":"Reports","type":"MIS Report - Board Pack","priority":"Critical","prompt":"Board MIS Pack: Revenue Rs.1,06,01,948 vs budget Rs.95,00,000 (+11.6%). Export USD 56,600 + GBP 49,280. GM 62%. EBITDA Rs.77,17,348 (73%). Cash Rs.91,40,000 + EEFC USD 33,000. Backlog Rs.1,20,00,000. Headcount 21. RBL Bank deal pending Rs.49,40,000. Board pack ready.","accounting":"Board MIS - summarizes entire month and FY","integrity":"Board reporting accuracy"},
]

TIMESHEET_ENTRIES = [
    # Week 1 (02-07 Mar)
    {"employee_id":"E005","employee_name":"Sneha Joshi","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-001","hours":32,"billable":True},{"project_id":"PRJ-INT","hours":4,"billable":False,"note":"Demo prep"},{"project_id":"PRJ-005","hours":4,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E006","employee_name":"Amit Rathod","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-001","hours":36,"billable":True,"ot_hours":2},{"project_id":"PRJ-005","hours":4,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E007","employee_name":"Rahul Dev","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-002","hours":32,"billable":True,"currency":"USD","rate":95},{"project_id":"PRJ-006","hours":8,"billable":True,"currency":"GBP","rate":140}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E012","employee_name":"Kiran Pillai","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-001","hours":24,"billable":True},{"project_id":"PRJ-004","hours":12,"billable":True},{"project_id":"PRJ-INT","hours":4,"billable":False,"note":"Training"}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E009","employee_name":"Ananya Singh","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-003","hours":28,"billable":True},{"project_id":"PRJ-007","hours":12,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E011","employee_name":"Divya Mehta","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-001","hours":32,"billable":True}],"total_hours":32,"status":"Approved","leave_hours":8,"leave_type":"Sick Leave"},
    {"employee_id":"E014","employee_name":"Meera Das","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-INT","hours":32,"billable":False,"note":"Bench"},{"project_id":"PRJ-INT","hours":8,"billable":False,"note":"Training - Figma"}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E015","employee_name":"Yash Trivedi","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-005","hours":20,"billable":True},{"project_id":"PRJ-INT","hours":20,"billable":False,"note":"Bench"}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E013","employee_name":"Fatima Khan","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-002","hours":20,"billable":True},{"project_id":"PRJ-007","hours":20,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E010","employee_name":"Siddharth Roy","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-003","hours":28,"billable":True},{"project_id":"PRJ-007","hours":12,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E008","employee_name":"Suresh Babu","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-004","hours":32,"billable":True},{"project_id":"PRJ-002","hours":8,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E016","employee_name":"Om Tiwari","week":"W1","week_start":"02-Mar-26","week_end":"07-Mar-26","entries":[{"project_id":"PRJ-INT","hours":40,"billable":False,"note":"New Employee Orientation"}],"total_hours":40,"status":"Approved"},
    # Week 2 (09-14 Mar)
    {"employee_id":"E005","employee_name":"Sneha Joshi","week":"W2","week_start":"09-Mar-26","week_end":"14-Mar-26","entries":[{"project_id":"PRJ-001","hours":32,"billable":True},{"project_id":"PRJ-005","hours":8,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E006","employee_name":"Amit Rathod","week":"W2","week_start":"09-Mar-26","week_end":"14-Mar-26","entries":[{"project_id":"PRJ-001","hours":40,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E007","employee_name":"Rahul Dev","week":"W2","week_start":"09-Mar-26","week_end":"14-Mar-26","entries":[{"project_id":"PRJ-002","hours":24,"billable":True,"currency":"USD","rate":95},{"project_id":"PRJ-006","hours":16,"billable":True,"currency":"GBP","rate":140}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E008","employee_name":"Suresh Babu","week":"W2","week_start":"09-Mar-26","week_end":"14-Mar-26","entries":[{"project_id":"PRJ-004","hours":32,"billable":True},{"project_id":"PRJ-002","hours":8,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E016","employee_name":"Om Tiwari","week":"W2","week_start":"09-Mar-26","week_end":"14-Mar-26","entries":[{"project_id":"PRJ-INT","hours":40,"billable":False,"note":"Training - AWS onboarding"}],"total_hours":40,"status":"Approved"},
    # Week 3 (16-21 Mar)
    {"employee_id":"E005","employee_name":"Sneha Joshi","week":"W3","week_start":"16-Mar-26","week_end":"21-Mar-26","entries":[{"project_id":"PRJ-001","hours":40,"billable":True,"ot_hours":4}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E006","employee_name":"Amit Rathod","week":"W3","week_start":"16-Mar-26","week_end":"21-Mar-26","entries":[{"project_id":"PRJ-001","hours":36,"billable":True},{"project_id":"PRJ-005","hours":4,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E007","employee_name":"Rahul Dev","week":"W3","week_start":"16-Mar-26","week_end":"21-Mar-26","entries":[{"project_id":"PRJ-002","hours":16,"billable":True,"currency":"USD","rate":95},{"project_id":"PRJ-006","hours":24,"billable":True,"currency":"GBP","rate":140}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E016","employee_name":"Om Tiwari","week":"W3","week_start":"16-Mar-26","week_end":"21-Mar-26","entries":[{"project_id":"PRJ-006","hours":24,"billable":True,"currency":"GBP","rate":140}],"total_hours":24,"status":"Approved"},
    {"employee_id":"E009","employee_name":"Ananya Singh","week":"W3","week_start":"16-Mar-26","week_end":"21-Mar-26","entries":[{"project_id":"PRJ-003","hours":32,"billable":True},{"project_id":"PRJ-007","hours":8,"billable":True}],"total_hours":40,"status":"Approved"},
    # Week 4 (23-28 Mar)
    {"employee_id":"E003","employee_name":"Priya Menon","week":"W4","week_start":"23-Mar-26","week_end":"28-Mar-26","entries":[{"project_id":"PRJ-005","hours":32,"billable":True},{"project_id":"PRJ-002","hours":8,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E005","employee_name":"Sneha Joshi","week":"W4","week_start":"23-Mar-26","week_end":"28-Mar-26","entries":[{"project_id":"PRJ-001","hours":32,"billable":True},{"project_id":"PRJ-005","hours":8,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E007","employee_name":"Rahul Dev","week":"W4","week_start":"23-Mar-26","week_end":"28-Mar-26","entries":[{"project_id":"PRJ-002","hours":24,"billable":True,"currency":"USD","rate":95},{"project_id":"PRJ-006","hours":16,"billable":True,"currency":"GBP","rate":140}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E010","employee_name":"Siddharth Roy","week":"W4","week_start":"23-Mar-26","week_end":"28-Mar-26","entries":[{"project_id":"PRJ-003","hours":24,"billable":True},{"project_id":"PRJ-007","hours":16,"billable":True}],"total_hours":40,"status":"Approved"},
    {"employee_id":"E013","employee_name":"Fatima Khan","week":"W4","week_start":"23-Mar-26","week_end":"28-Mar-26","entries":[{"project_id":"PRJ-002","hours":16,"billable":True},{"project_id":"PRJ-007","hours":24,"billable":True}],"total_hours":40,"status":"Approved"},
]

# Monthly hours consolidation
MONTHLY_HOURS = {
    "PRJ-001": {"hours":520,"rate_type":"Fixed-Price","currency":"INR"},
    "PRJ-002": {"hours":280,"rate_type":"T&M","rate_usd":95,"currency":"USD","billing_amount_usd":26600},
    "PRJ-003": {"hours":280,"rate_type":"Milestone","currency":"INR"},
    "PRJ-004": {"hours":160,"rate_type":"Retainer","currency":"INR","fixed_monthly":450000},
    "PRJ-005": {"hours":120,"rate_type":"Fixed-Price Export","currency":"USD"},
    "PRJ-006": {"hours":224,"rate_type":"T&M Export","rate_gbp":140,"currency":"GBP","billing_amount_gbp":48160},
    "PRJ-007": {"hours":152,"rate_type":"Milestone","currency":"INR"},
}

async def seed():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    
    # Step 1: Clear all collections
    collections = await db.list_collection_names()
    for col in collections:
        await db[col].drop()
    print(f"Cleared {len(collections)} collections")
    
    # Step 2: Seed company settings
    await db.company_settings.insert_one(CO)
    print("Seeded company settings: Nexora Digital Solutions")
    
    # Step 3: Seed projects
    for p in PROJECTS:
        p["created_at"] = datetime.now(timezone.utc).isoformat()
    await db.projects.insert_many(PROJECTS)
    print(f"Seeded {len(PROJECTS)} projects")
    
    # Step 4: Seed employees
    for e in EMPLOYEES:
        e["created_at"] = datetime.now(timezone.utc).isoformat()
    await db.employees.insert_many(EMPLOYEES)
    print(f"Seeded {len(EMPLOYEES)} employees")
    
    # Step 5: Seed clients as entities
    for c in CLIENTS:
        c["created_at"] = datetime.now(timezone.utc).isoformat()
        c["gstin_valid"] = c["gstin"] not in ["EXPORT"]
        c["gst_state_code"] = c.get("state_code", "")
    await db.entities.insert_many(CLIENTS)
    print(f"Seeded {len(CLIENTS)} clients")
    
    # Step 6: Seed vendors as entities
    for v in VENDORS:
        v["created_at"] = datetime.now(timezone.utc).isoformat()
        v["gstin_valid"] = v["gstin"] not in ["IMPORT"]
        v["gst_state_code"] = v.get("state_code", "")
    await db.entities.insert_many(VENDORS)
    print(f"Seeded {len(VENDORS)} vendors")
    
    # Step 7: Seed Chart of Accounts from Opening TB
    coa_entries = []
    for entry in OPENING_TB:
        coa_entries.append({
            "id": str(uuid.uuid4()),
            "ledger_name": entry["account"],
            "category": entry["category"],
            "sub_category": entry.get("sub_category", ""),
            "account_type": entry["type"],
            "opening_balance": entry["debit"] - entry["credit"],
            "current_balance": entry["debit"] - entry["credit"],
            "is_active": True,
            "note": entry.get("note", ""),
            "created_at": datetime.now(timezone.utc).isoformat(),
        })
    await db.chart_of_accounts.insert_many(coa_entries)
    print(f"Seeded {len(coa_entries)} chart of accounts entries")
    
    # Step 8: Seed Revenue Schedule
    for r in REV_SCHEDULE:
        r["created_at"] = datetime.now(timezone.utc).isoformat()
    await db.revenue_schedule.insert_many(REV_SCHEDULE)
    print(f"Seeded {len(REV_SCHEDULE)} revenue schedule entries")
    
    # Step 9: Seed Transactions
    for t in TRANSACTIONS:
        t["created_at"] = datetime.now(timezone.utc).isoformat()
    await db.erp_transactions.insert_many(TRANSACTIONS)
    print(f"Seeded {len(TRANSACTIONS)} transactions")
    
    # Step 10: Seed Timesheet Entries
    for ts in TIMESHEET_ENTRIES:
        ts["created_at"] = datetime.now(timezone.utc).isoformat()
        ts["id"] = str(uuid.uuid4())
    await db.timesheets.insert_many(TIMESHEET_ENTRIES)
    print(f"Seeded {len(TIMESHEET_ENTRIES)} timesheet entries")
    
    # Step 11: Seed Monthly Hours Consolidation
    await db.monthly_hours.insert_one({"period":"March 2026","data":MONTHLY_HOURS,"created_at":datetime.now(timezone.utc).isoformat()})
    print("Seeded monthly hours consolidation")
    
    # Verify
    total_dr = sum(e["debit"] for e in OPENING_TB)
    total_cr = sum(e["credit"] for e in OPENING_TB)
    print(f"\nOpening TB: Dr={total_dr:,.0f} Cr={total_cr:,.0f} Balanced={'YES' if total_dr == total_cr else 'NO'}")
    print(f"Transactions by module:")
    from collections import Counter
    mod_counts = Counter(t["module"] for t in TRANSACTIONS)
    for mod, count in sorted(mod_counts.items()):
        print(f"  {mod}: {count}")
    print("\nSeed complete!")
    
    client.close()

if __name__ == "__main__":
    asyncio.run(seed())
